// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// HeartbeatEventHandler is an autogenerated mock type for the HeartbeatEventHandler type
type HeartbeatEventHandler struct {
	mock.Mock
}

// OnHeartbeatTimeout provides a mock function with given fields: view, leaderID
func (_m *HeartbeatEventHandler) OnHeartbeatTimeout(view uint64, leaderID uint64) {
	_m.Called(view, leaderID)
}

// Sync provides a mock function with given fields:
func (_m *HeartbeatEventHandler) Sync() {
	_m.Called()
}
