// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import types "github.com/SmartBFT-Go/consensus/v2/pkg/types"

// RequestTimeoutHandler is an autogenerated mock type for the RequestTimeoutHandler type
type RequestTimeoutHandler struct {
	mock.Mock
}

// OnAutoRemoveTimeout provides a mock function with given fields: requestInfo
func (_m *RequestTimeoutHandler) OnAutoRemoveTimeout(requestInfo types.RequestInfo) {
	_m.Called(requestInfo)
}

// OnLeaderFwdRequestTimeout provides a mock function with given fields: request, requestInfo
func (_m *RequestTimeoutHandler) OnLeaderFwdRequestTimeout(request []byte, requestInfo types.RequestInfo) {
	_m.Called(request, requestInfo)
}

// OnRequestTimeout provides a mock function with given fields: request, requestInfo
func (_m *RequestTimeoutHandler) OnRequestTimeout(request []byte, requestInfo types.RequestInfo) {
	_m.Called(request, requestInfo)
}
