// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test_messages.proto

package test

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FwdMessage struct {
	Sender               uint64   `protobuf:"varint,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Payload              []byte   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FwdMessage) Reset()         { *m = FwdMessage{} }
func (m *FwdMessage) String() string { return proto.CompactTextString(m) }
func (*FwdMessage) ProtoMessage()    {}
func (*FwdMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_c470e08e348a5935, []int{0}
}

func (m *FwdMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FwdMessage.Unmarshal(m, b)
}
func (m *FwdMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FwdMessage.Marshal(b, m, deterministic)
}
func (m *FwdMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FwdMessage.Merge(m, src)
}
func (m *FwdMessage) XXX_Size() int {
	return xxx_messageInfo_FwdMessage.Size(m)
}
func (m *FwdMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_FwdMessage.DiscardUnknown(m)
}

var xxx_messageInfo_FwdMessage proto.InternalMessageInfo

func (m *FwdMessage) GetSender() uint64 {
	if m != nil {
		return m.Sender
	}
	return 0
}

func (m *FwdMessage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*FwdMessage)(nil), "test.fwdMessage")
}

func init() { proto.RegisterFile("test_messages.proto", fileDescriptor_c470e08e348a5935) }

var fileDescriptor_c470e08e348a5935 = []byte{
	// 102 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x49, 0x2d, 0x2e,
	0x89, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x62, 0x01, 0x09, 0x2a, 0xd9, 0x71, 0x71, 0xa5, 0x95, 0xa7, 0xf8, 0x42, 0xa4, 0x84, 0xc4, 0xb8,
	0xd8, 0x8a, 0x53, 0xf3, 0x52, 0x52, 0x8b, 0x24, 0x18, 0x15, 0x18, 0x35, 0x58, 0x82, 0xa0, 0x3c,
	0x21, 0x09, 0x2e, 0xf6, 0x82, 0xc4, 0xca, 0x9c, 0xfc, 0xc4, 0x14, 0x09, 0x26, 0x05, 0x46, 0x0d,
	0x9e, 0x20, 0x18, 0x37, 0x89, 0x0d, 0x6c, 0x98, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x1e, 0xa3,
	0x10, 0x67, 0x63, 0x00, 0x00, 0x00,
}
