// Copyright IBM Corp. All Rights Reserved.
//
// SPDX-License-Identifier: Apache-2.0
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: test/test_messages.proto

package test

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FwdMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        uint64                 `protobuf:"varint,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FwdMessage) Reset() {
	*x = FwdMessage{}
	mi := &file_test_test_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FwdMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FwdMessage) ProtoMessage() {}

func (x *FwdMessage) ProtoReflect() protoreflect.Message {
	mi := &file_test_test_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FwdMessage.ProtoReflect.Descriptor instead.
func (*FwdMessage) Descriptor() ([]byte, []int) {
	return file_test_test_messages_proto_rawDescGZIP(), []int{0}
}

func (x *FwdMessage) GetSender() uint64 {
	if x != nil {
		return x.Sender
	}
	return 0
}

func (x *FwdMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_test_test_messages_proto protoreflect.FileDescriptor

const file_test_test_messages_proto_rawDesc = "" +
	"\n" +
	"\x18test/test_messages.proto\x12\x04test\">\n" +
	"\n" +
	"fwdMessage\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\x04R\x06sender\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayloadB+Z)github.com/hyperledger-labs/SmartBFT/testb\x06proto3"

var (
	file_test_test_messages_proto_rawDescOnce sync.Once
	file_test_test_messages_proto_rawDescData []byte
)

func file_test_test_messages_proto_rawDescGZIP() []byte {
	file_test_test_messages_proto_rawDescOnce.Do(func() {
		file_test_test_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_test_messages_proto_rawDesc), len(file_test_test_messages_proto_rawDesc)))
	})
	return file_test_test_messages_proto_rawDescData
}

var file_test_test_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_test_test_messages_proto_goTypes = []any{
	(*FwdMessage)(nil), // 0: test.fwdMessage
}
var file_test_test_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_test_test_messages_proto_init() }
func file_test_test_messages_proto_init() {
	if File_test_test_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_test_messages_proto_rawDesc), len(file_test_test_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_test_messages_proto_goTypes,
		DependencyIndexes: file_test_test_messages_proto_depIdxs,
		MessageInfos:      file_test_test_messages_proto_msgTypes,
	}.Build()
	File_test_test_messages_proto = out.File
	file_test_test_messages_proto_goTypes = nil
	file_test_test_messages_proto_depIdxs = nil
}
