// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/schema.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	// Types that are valid to be assigned to Content:
	//	*Message_PrePrepare
	//	*Message_Prepare
	//	*Message_Commit
	//	*Message_Error
	//	*Message_ViewChange
	//	*Message_ViewData
	//	*Message_NewView
	//	*Message_HeartBeat
	Content              isMessage_Content `protobuf_oneof:"content"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ba2179f55c66160, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

type isMessage_Content interface {
	isMessage_Content()
}

type Message_PrePrepare struct {
	PrePrepare *PrePrepare `protobuf:"bytes,1,opt,name=pre_prepare,json=prePrepare,proto3,oneof"`
}

type Message_Prepare struct {
	Prepare *Prepare `protobuf:"bytes,2,opt,name=prepare,proto3,oneof"`
}

type Message_Commit struct {
	Commit *Commit `protobuf:"bytes,3,opt,name=commit,proto3,oneof"`
}

type Message_Error struct {
	Error *Error `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

type Message_ViewChange struct {
	ViewChange *ViewChange `protobuf:"bytes,5,opt,name=view_change,json=viewChange,proto3,oneof"`
}

type Message_ViewData struct {
	ViewData *SignedViewData `protobuf:"bytes,6,opt,name=view_data,json=viewData,proto3,oneof"`
}

type Message_NewView struct {
	NewView *NewView `protobuf:"bytes,7,opt,name=new_view,json=newView,proto3,oneof"`
}

type Message_HeartBeat struct {
	HeartBeat *HeartBeat `protobuf:"bytes,8,opt,name=heart_beat,json=heartBeat,proto3,oneof"`
}

func (*Message_PrePrepare) isMessage_Content() {}

func (*Message_Prepare) isMessage_Content() {}

func (*Message_Commit) isMessage_Content() {}

func (*Message_Error) isMessage_Content() {}

func (*Message_ViewChange) isMessage_Content() {}

func (*Message_ViewData) isMessage_Content() {}

func (*Message_NewView) isMessage_Content() {}

func (*Message_HeartBeat) isMessage_Content() {}

func (m *Message) GetContent() isMessage_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Message) GetPrePrepare() *PrePrepare {
	if x, ok := m.GetContent().(*Message_PrePrepare); ok {
		return x.PrePrepare
	}
	return nil
}

func (m *Message) GetPrepare() *Prepare {
	if x, ok := m.GetContent().(*Message_Prepare); ok {
		return x.Prepare
	}
	return nil
}

func (m *Message) GetCommit() *Commit {
	if x, ok := m.GetContent().(*Message_Commit); ok {
		return x.Commit
	}
	return nil
}

func (m *Message) GetError() *Error {
	if x, ok := m.GetContent().(*Message_Error); ok {
		return x.Error
	}
	return nil
}

func (m *Message) GetViewChange() *ViewChange {
	if x, ok := m.GetContent().(*Message_ViewChange); ok {
		return x.ViewChange
	}
	return nil
}

func (m *Message) GetViewData() *SignedViewData {
	if x, ok := m.GetContent().(*Message_ViewData); ok {
		return x.ViewData
	}
	return nil
}

func (m *Message) GetNewView() *NewView {
	if x, ok := m.GetContent().(*Message_NewView); ok {
		return x.NewView
	}
	return nil
}

func (m *Message) GetHeartBeat() *HeartBeat {
	if x, ok := m.GetContent().(*Message_HeartBeat); ok {
		return x.HeartBeat
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Message) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Message_PrePrepare)(nil),
		(*Message_Prepare)(nil),
		(*Message_Commit)(nil),
		(*Message_Error)(nil),
		(*Message_ViewChange)(nil),
		(*Message_ViewData)(nil),
		(*Message_NewView)(nil),
		(*Message_HeartBeat)(nil),
	}
}

type PrePrepare struct {
	View                 uint64    `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	Seq                  uint64    `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Proposal             *Proposal `protobuf:"bytes,3,opt,name=proposal,proto3" json:"proposal,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PrePrepare) Reset()         { *m = PrePrepare{} }
func (m *PrePrepare) String() string { return proto.CompactTextString(m) }
func (*PrePrepare) ProtoMessage()    {}
func (*PrePrepare) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ba2179f55c66160, []int{1}
}

func (m *PrePrepare) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrePrepare.Unmarshal(m, b)
}
func (m *PrePrepare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrePrepare.Marshal(b, m, deterministic)
}
func (m *PrePrepare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrePrepare.Merge(m, src)
}
func (m *PrePrepare) XXX_Size() int {
	return xxx_messageInfo_PrePrepare.Size(m)
}
func (m *PrePrepare) XXX_DiscardUnknown() {
	xxx_messageInfo_PrePrepare.DiscardUnknown(m)
}

var xxx_messageInfo_PrePrepare proto.InternalMessageInfo

func (m *PrePrepare) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *PrePrepare) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *PrePrepare) GetProposal() *Proposal {
	if m != nil {
		return m.Proposal
	}
	return nil
}

type Prepare struct {
	View                 uint64   `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	Seq                  uint64   `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Digest               []byte   `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Prepare) Reset()         { *m = Prepare{} }
func (m *Prepare) String() string { return proto.CompactTextString(m) }
func (*Prepare) ProtoMessage()    {}
func (*Prepare) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ba2179f55c66160, []int{2}
}

func (m *Prepare) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Prepare.Unmarshal(m, b)
}
func (m *Prepare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Prepare.Marshal(b, m, deterministic)
}
func (m *Prepare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Prepare.Merge(m, src)
}
func (m *Prepare) XXX_Size() int {
	return xxx_messageInfo_Prepare.Size(m)
}
func (m *Prepare) XXX_DiscardUnknown() {
	xxx_messageInfo_Prepare.DiscardUnknown(m)
}

var xxx_messageInfo_Prepare proto.InternalMessageInfo

func (m *Prepare) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *Prepare) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *Prepare) GetDigest() []byte {
	if m != nil {
		return m.Digest
	}
	return nil
}

type Commit struct {
	View                 uint64     `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	Seq                  uint64     `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Digest               []byte     `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	Signature            *Signature `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Commit) Reset()         { *m = Commit{} }
func (m *Commit) String() string { return proto.CompactTextString(m) }
func (*Commit) ProtoMessage()    {}
func (*Commit) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ba2179f55c66160, []int{3}
}

func (m *Commit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Commit.Unmarshal(m, b)
}
func (m *Commit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Commit.Marshal(b, m, deterministic)
}
func (m *Commit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Commit.Merge(m, src)
}
func (m *Commit) XXX_Size() int {
	return xxx_messageInfo_Commit.Size(m)
}
func (m *Commit) XXX_DiscardUnknown() {
	xxx_messageInfo_Commit.DiscardUnknown(m)
}

var xxx_messageInfo_Commit proto.InternalMessageInfo

func (m *Commit) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *Commit) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *Commit) GetDigest() []byte {
	if m != nil {
		return m.Digest
	}
	return nil
}

func (m *Commit) GetSignature() *Signature {
	if m != nil {
		return m.Signature
	}
	return nil
}

type Error struct {
	View                 uint64   `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	Seq                  uint64   `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Digest               []byte   `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	Reason               string   `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ba2179f55c66160, []int{4}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *Error) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *Error) GetDigest() []byte {
	if m != nil {
		return m.Digest
	}
	return nil
}

func (m *Error) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type ViewChange struct {
	NextView             uint64   `protobuf:"varint,1,opt,name=next_view,json=nextView,proto3" json:"next_view,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ViewChange) Reset()         { *m = ViewChange{} }
func (m *ViewChange) String() string { return proto.CompactTextString(m) }
func (*ViewChange) ProtoMessage()    {}
func (*ViewChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ba2179f55c66160, []int{5}
}

func (m *ViewChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewChange.Unmarshal(m, b)
}
func (m *ViewChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewChange.Marshal(b, m, deterministic)
}
func (m *ViewChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewChange.Merge(m, src)
}
func (m *ViewChange) XXX_Size() int {
	return xxx_messageInfo_ViewChange.Size(m)
}
func (m *ViewChange) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewChange.DiscardUnknown(m)
}

var xxx_messageInfo_ViewChange proto.InternalMessageInfo

func (m *ViewChange) GetNextView() uint64 {
	if m != nil {
		return m.NextView
	}
	return 0
}

func (m *ViewChange) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type ViewData struct {
	NextView               uint64       `protobuf:"varint,1,opt,name=next_view,json=nextView,proto3" json:"next_view,omitempty"`
	LastDecision           *Proposal    `protobuf:"bytes,2,opt,name=last_decision,json=lastDecision,proto3" json:"last_decision,omitempty"`
	LastDecisionSignatures []*Signature `protobuf:"bytes,3,rep,name=last_decision_signatures,json=lastDecisionSignatures,proto3" json:"last_decision_signatures,omitempty"`
	LastPrePrepare         *PrePrepare  `protobuf:"bytes,4,opt,name=last_pre_prepare,json=lastPrePrepare,proto3" json:"last_pre_prepare,omitempty"`
	LastPrepare            *Prepare     `protobuf:"bytes,5,opt,name=last_prepare,json=lastPrepare,proto3" json:"last_prepare,omitempty"`
	LastCommit             *Commit      `protobuf:"bytes,6,opt,name=last_commit,json=lastCommit,proto3" json:"last_commit,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}     `json:"-"`
	XXX_unrecognized       []byte       `json:"-"`
	XXX_sizecache          int32        `json:"-"`
}

func (m *ViewData) Reset()         { *m = ViewData{} }
func (m *ViewData) String() string { return proto.CompactTextString(m) }
func (*ViewData) ProtoMessage()    {}
func (*ViewData) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ba2179f55c66160, []int{6}
}

func (m *ViewData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewData.Unmarshal(m, b)
}
func (m *ViewData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewData.Marshal(b, m, deterministic)
}
func (m *ViewData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewData.Merge(m, src)
}
func (m *ViewData) XXX_Size() int {
	return xxx_messageInfo_ViewData.Size(m)
}
func (m *ViewData) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewData.DiscardUnknown(m)
}

var xxx_messageInfo_ViewData proto.InternalMessageInfo

func (m *ViewData) GetNextView() uint64 {
	if m != nil {
		return m.NextView
	}
	return 0
}

func (m *ViewData) GetLastDecision() *Proposal {
	if m != nil {
		return m.LastDecision
	}
	return nil
}

func (m *ViewData) GetLastDecisionSignatures() []*Signature {
	if m != nil {
		return m.LastDecisionSignatures
	}
	return nil
}

func (m *ViewData) GetLastPrePrepare() *PrePrepare {
	if m != nil {
		return m.LastPrePrepare
	}
	return nil
}

func (m *ViewData) GetLastPrepare() *Prepare {
	if m != nil {
		return m.LastPrepare
	}
	return nil
}

func (m *ViewData) GetLastCommit() *Commit {
	if m != nil {
		return m.LastCommit
	}
	return nil
}

type SignedViewData struct {
	RawViewData          []byte     `protobuf:"bytes,1,opt,name=raw_view_data,json=rawViewData,proto3" json:"raw_view_data,omitempty"`
	Signature            *Signature `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SignedViewData) Reset()         { *m = SignedViewData{} }
func (m *SignedViewData) String() string { return proto.CompactTextString(m) }
func (*SignedViewData) ProtoMessage()    {}
func (*SignedViewData) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ba2179f55c66160, []int{7}
}

func (m *SignedViewData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedViewData.Unmarshal(m, b)
}
func (m *SignedViewData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedViewData.Marshal(b, m, deterministic)
}
func (m *SignedViewData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedViewData.Merge(m, src)
}
func (m *SignedViewData) XXX_Size() int {
	return xxx_messageInfo_SignedViewData.Size(m)
}
func (m *SignedViewData) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedViewData.DiscardUnknown(m)
}

var xxx_messageInfo_SignedViewData proto.InternalMessageInfo

func (m *SignedViewData) GetRawViewData() []byte {
	if m != nil {
		return m.RawViewData
	}
	return nil
}

func (m *SignedViewData) GetSignature() *Signature {
	if m != nil {
		return m.Signature
	}
	return nil
}

type NewView struct {
	SignedViewData       []*SignedViewData `protobuf:"bytes,2,rep,name=signed_view_data,json=signedViewData,proto3" json:"signed_view_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *NewView) Reset()         { *m = NewView{} }
func (m *NewView) String() string { return proto.CompactTextString(m) }
func (*NewView) ProtoMessage()    {}
func (*NewView) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ba2179f55c66160, []int{8}
}

func (m *NewView) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewView.Unmarshal(m, b)
}
func (m *NewView) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewView.Marshal(b, m, deterministic)
}
func (m *NewView) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewView.Merge(m, src)
}
func (m *NewView) XXX_Size() int {
	return xxx_messageInfo_NewView.Size(m)
}
func (m *NewView) XXX_DiscardUnknown() {
	xxx_messageInfo_NewView.DiscardUnknown(m)
}

var xxx_messageInfo_NewView proto.InternalMessageInfo

func (m *NewView) GetSignedViewData() []*SignedViewData {
	if m != nil {
		return m.SignedViewData
	}
	return nil
}

type HeartBeat struct {
	View                 int64    `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	Seq                  uint64   `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartBeat) Reset()         { *m = HeartBeat{} }
func (m *HeartBeat) String() string { return proto.CompactTextString(m) }
func (*HeartBeat) ProtoMessage()    {}
func (*HeartBeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ba2179f55c66160, []int{9}
}

func (m *HeartBeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartBeat.Unmarshal(m, b)
}
func (m *HeartBeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartBeat.Marshal(b, m, deterministic)
}
func (m *HeartBeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartBeat.Merge(m, src)
}
func (m *HeartBeat) XXX_Size() int {
	return xxx_messageInfo_HeartBeat.Size(m)
}
func (m *HeartBeat) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartBeat.DiscardUnknown(m)
}

var xxx_messageInfo_HeartBeat proto.InternalMessageInfo

func (m *HeartBeat) GetView() int64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *HeartBeat) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

type Signature struct {
	Signer               uint64   `protobuf:"varint,1,opt,name=signer,proto3" json:"signer,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Signature) Reset()         { *m = Signature{} }
func (m *Signature) String() string { return proto.CompactTextString(m) }
func (*Signature) ProtoMessage()    {}
func (*Signature) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ba2179f55c66160, []int{10}
}

func (m *Signature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Signature.Unmarshal(m, b)
}
func (m *Signature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Signature.Marshal(b, m, deterministic)
}
func (m *Signature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Signature.Merge(m, src)
}
func (m *Signature) XXX_Size() int {
	return xxx_messageInfo_Signature.Size(m)
}
func (m *Signature) XXX_DiscardUnknown() {
	xxx_messageInfo_Signature.DiscardUnknown(m)
}

var xxx_messageInfo_Signature proto.InternalMessageInfo

func (m *Signature) GetSigner() uint64 {
	if m != nil {
		return m.Signer
	}
	return 0
}

func (m *Signature) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type Proposal struct {
	Header               []byte   `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Payload              []byte   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Metadata             []byte   `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	VerificationSequence uint64   `protobuf:"varint,4,opt,name=verification_sequence,json=verificationSequence,proto3" json:"verification_sequence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Proposal) Reset()         { *m = Proposal{} }
func (m *Proposal) String() string { return proto.CompactTextString(m) }
func (*Proposal) ProtoMessage()    {}
func (*Proposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ba2179f55c66160, []int{11}
}

func (m *Proposal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Proposal.Unmarshal(m, b)
}
func (m *Proposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Proposal.Marshal(b, m, deterministic)
}
func (m *Proposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proposal.Merge(m, src)
}
func (m *Proposal) XXX_Size() int {
	return xxx_messageInfo_Proposal.Size(m)
}
func (m *Proposal) XXX_DiscardUnknown() {
	xxx_messageInfo_Proposal.DiscardUnknown(m)
}

var xxx_messageInfo_Proposal proto.InternalMessageInfo

func (m *Proposal) GetHeader() []byte {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Proposal) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Proposal) GetMetadata() []byte {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Proposal) GetVerificationSequence() uint64 {
	if m != nil {
		return m.VerificationSequence
	}
	return 0
}

func init() {
	proto.RegisterType((*Message)(nil), "protos.Message")
	proto.RegisterType((*PrePrepare)(nil), "protos.PrePrepare")
	proto.RegisterType((*Prepare)(nil), "protos.Prepare")
	proto.RegisterType((*Commit)(nil), "protos.Commit")
	proto.RegisterType((*Error)(nil), "protos.Error")
	proto.RegisterType((*ViewChange)(nil), "protos.ViewChange")
	proto.RegisterType((*ViewData)(nil), "protos.ViewData")
	proto.RegisterType((*SignedViewData)(nil), "protos.SignedViewData")
	proto.RegisterType((*NewView)(nil), "protos.NewView")
	proto.RegisterType((*HeartBeat)(nil), "protos.HeartBeat")
	proto.RegisterType((*Signature)(nil), "protos.Signature")
	proto.RegisterType((*Proposal)(nil), "protos.Proposal")
}

func init() { proto.RegisterFile("protos/schema.proto", fileDescriptor_1ba2179f55c66160) }

var fileDescriptor_1ba2179f55c66160 = []byte{
	// 669 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xdd, 0x6a, 0xd4, 0x40,
	0x14, 0xde, 0xff, 0x24, 0x67, 0xb7, 0xeb, 0x76, 0xac, 0x4b, 0xd0, 0x9b, 0x12, 0x10, 0x0a, 0x4a,
	0x8b, 0x2d, 0xbd, 0x10, 0xbc, 0xd0, 0xb6, 0xe2, 0x42, 0x51, 0xca, 0x14, 0xbc, 0x93, 0x38, 0xcd,
	0x1e, 0x77, 0x03, 0xbb, 0x49, 0x3a, 0x93, 0xee, 0xea, 0x43, 0xf8, 0x00, 0xbe, 0x94, 0xcf, 0x24,
	0x73, 0x66, 0x92, 0x4d, 0x60, 0x2b, 0x4a, 0xef, 0xf2, 0xcd, 0xf9, 0xbe, 0x33, 0x3f, 0xe7, 0x3b,
	0x27, 0xf0, 0x38, 0x93, 0x69, 0x9e, 0xaa, 0x23, 0x15, 0xcd, 0x71, 0x29, 0x0e, 0x09, 0xb1, 0x9e,
	0x59, 0x0c, 0x7e, 0xb5, 0xc1, 0xf9, 0x88, 0x4a, 0x89, 0x19, 0xb2, 0x53, 0xe8, 0x67, 0x12, 0xc3,
	0x4c, 0x62, 0x26, 0x24, 0xfa, 0xcd, 0xfd, 0xe6, 0x41, 0xff, 0x98, 0x19, 0x81, 0x3a, 0xbc, 0x92,
	0x78, 0x65, 0x22, 0x93, 0x06, 0x87, 0xac, 0x44, 0xec, 0x05, 0x38, 0x85, 0xa4, 0x45, 0x92, 0x47,
	0x15, 0x89, 0xe5, 0x17, 0x0c, 0x76, 0x00, 0xbd, 0x28, 0x5d, 0x2e, 0xe3, 0xdc, 0x6f, 0x13, 0x77,
	0x58, 0x70, 0xcf, 0x69, 0x75, 0xd2, 0xe0, 0x36, 0xce, 0x9e, 0x43, 0x17, 0xa5, 0x4c, 0xa5, 0xdf,
	0x21, 0xe2, 0x4e, 0x41, 0x7c, 0xaf, 0x17, 0x27, 0x0d, 0x6e, 0xa2, 0xfa, 0xd0, 0xab, 0x18, 0xd7,
	0x61, 0x34, 0x17, 0xc9, 0x0c, 0xfd, 0x6e, 0xfd, 0xd0, 0x9f, 0x63, 0x5c, 0x9f, 0x53, 0x44, 0x1f,
	0x7a, 0x55, 0x22, 0x76, 0x0a, 0x1e, 0xc9, 0xa6, 0x22, 0x17, 0x7e, 0x8f, 0x44, 0xe3, 0x42, 0x74,
	0x1d, 0xcf, 0x12, 0x9c, 0x6a, 0xe9, 0x85, 0xc8, 0xc5, 0xa4, 0xc1, 0xdd, 0x95, 0xfd, 0x66, 0x2f,
	0xc1, 0x4d, 0x70, 0x1d, 0x6a, 0xec, 0x3b, 0xf5, 0xcb, 0x7e, 0xc2, 0xb5, 0x96, 0xe8, 0xcb, 0x26,
	0xe6, 0x93, 0x1d, 0x03, 0xcc, 0x51, 0xc8, 0x3c, 0xbc, 0x41, 0x91, 0xfb, 0x2e, 0xf1, 0x77, 0x0b,
	0xfe, 0x44, 0x47, 0xce, 0x50, 0xe8, 0x3b, 0x7b, 0xf3, 0x02, 0x9c, 0x79, 0xe0, 0x44, 0x69, 0x92,
	0x63, 0x92, 0x07, 0x5f, 0x01, 0x36, 0x8f, 0xce, 0x18, 0x74, 0x68, 0x5b, 0x5d, 0x96, 0x0e, 0xa7,
	0x6f, 0x36, 0x82, 0xb6, 0xc2, 0x5b, 0x7a, 0xf6, 0x0e, 0xd7, 0x9f, 0xfa, 0x80, 0x99, 0x4c, 0xb3,
	0x54, 0x89, 0x85, 0x7d, 0xe1, 0xd1, 0xa6, 0x1a, 0x66, 0x9d, 0x97, 0x8c, 0xe0, 0x03, 0x38, 0xff,
	0x97, 0x7e, 0x0c, 0xbd, 0x69, 0x3c, 0x43, 0x65, 0xca, 0x37, 0xe0, 0x16, 0x05, 0x6b, 0xe8, 0x99,
	0x02, 0x3e, 0x2c, 0x0f, 0x3b, 0x02, 0x4f, 0xc5, 0xb3, 0x44, 0xe4, 0x77, 0x12, 0x6d, 0xe1, 0x77,
	0xab, 0x65, 0xa1, 0x00, 0xdf, 0x70, 0x82, 0x2f, 0xd0, 0x25, 0x43, 0x3c, 0x70, 0xdf, 0x31, 0xf4,
	0x24, 0x0a, 0x95, 0x26, 0xb4, 0xa9, 0xc7, 0x2d, 0x0a, 0xde, 0x01, 0x6c, 0x2c, 0xc4, 0x9e, 0x81,
	0x97, 0xe0, 0xf7, 0x3c, 0xac, 0x6c, 0xe4, 0xea, 0x05, 0x2a, 0xf6, 0x26, 0x45, 0xab, 0x96, 0xe2,
	0x77, 0x0b, 0xdc, 0xc2, 0x4b, 0x7f, 0xcf, 0x70, 0x0a, 0x3b, 0x0b, 0xa1, 0xf2, 0x70, 0x8a, 0x51,
	0xac, 0x62, 0x9b, 0x68, 0x5b, 0x01, 0x07, 0x9a, 0x76, 0x61, 0x59, 0xec, 0x12, 0xfc, 0x9a, 0x2c,
	0x2c, 0x5f, 0x47, 0xf9, 0xed, 0xfd, 0xf6, 0xf6, 0x27, 0x1c, 0x57, 0x53, 0x94, 0xcb, 0x8a, 0xbd,
	0x81, 0x11, 0x25, 0xab, 0x0e, 0x82, 0xce, 0x7d, 0x83, 0x80, 0x0f, 0x35, 0xb7, 0xe2, 0xd1, 0x63,
	0x18, 0x14, 0x6a, 0x52, 0x76, 0xb7, 0xce, 0x03, 0xde, 0xb7, 0x32, 0xd2, 0x1c, 0x01, 0xc1, 0xd0,
	0x8e, 0x85, 0xde, 0xb6, 0xb1, 0xc0, 0x41, 0x53, 0xcc, 0x77, 0x80, 0x30, 0xac, 0x77, 0x28, 0x0b,
	0x60, 0x47, 0x0a, 0xd3, 0x95, 0xa6, 0xa1, 0x9b, 0x54, 0xdc, 0xbe, 0x14, 0xeb, 0x92, 0x53, 0x73,
	0x56, 0xeb, 0x1f, 0x9c, 0x75, 0x09, 0x8e, 0x6d, 0x69, 0xf6, 0x16, 0x46, 0x8a, 0x76, 0xac, 0x6c,
	0xd1, 0xa2, 0x97, 0xbd, 0x67, 0x66, 0xf0, 0xa1, 0xaa, 0xe1, 0xe0, 0x15, 0x78, 0x65, 0xbf, 0xd7,
	0xac, 0xda, 0xbe, 0xcf, 0xaa, 0xc1, 0x6b, 0xf0, 0xca, 0x73, 0x69, 0x73, 0x51, 0x46, 0x69, 0x4d,
	0x63, 0x11, 0xdb, 0x83, 0xee, 0x4a, 0x2c, 0xee, 0xcc, 0x8d, 0x06, 0xdc, 0x80, 0xe0, 0x67, 0x13,
	0xdc, 0xc2, 0x2c, 0x5a, 0x3a, 0x47, 0x31, 0xb5, 0xd2, 0x01, 0xb7, 0x88, 0xf9, 0xe0, 0x64, 0xe2,
	0xc7, 0x22, 0x15, 0x53, 0x2b, 0x2e, 0x20, 0x7b, 0x0a, 0xee, 0x12, 0x73, 0x41, 0xd7, 0x34, 0x6d,
	0x52, 0x62, 0x76, 0x02, 0x4f, 0x56, 0x28, 0xe3, 0x6f, 0x71, 0x24, 0x72, 0xf2, 0x1a, 0xde, 0xde,
	0x61, 0x12, 0x19, 0x93, 0x74, 0xf8, 0x5e, 0x35, 0x78, 0x6d, 0x63, 0x37, 0xe6, 0x67, 0x73, 0xf2,
	0x27, 0x00, 0x00, 0xff, 0xff, 0x60, 0x33, 0x00, 0x8d, 0x8a, 0x06, 0x00, 0x00,
}
