// Code generated by protoc-gen-go. DO NOT EDIT.
// source: logrecord.proto

package smartbftprotos

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LogRecord_Type int32

const (
	LogRecord_ENTRY      LogRecord_Type = 0
	LogRecord_CONTROL    LogRecord_Type = 1
	LogRecord_CRC_ANCHOR LogRecord_Type = 2
)

var LogRecord_Type_name = map[int32]string{
	0: "ENTRY",
	1: "CONTROL",
	2: "CRC_ANCHOR",
}

var LogRecord_Type_value = map[string]int32{
	"ENTRY":      0,
	"CONTROL":    1,
	"CRC_ANCHOR": 2,
}

func (x LogRecord_Type) String() string {
	return proto.EnumName(LogRecord_Type_name, int32(x))
}

func (LogRecord_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6286842f97d51001, []int{0, 0}
}

type LogRecord struct {
	Type                 LogRecord_Type `protobuf:"varint,1,opt,name=type,proto3,enum=smartbftprotos.LogRecord_Type" json:"type,omitempty"`
	TruncateTo           bool           `protobuf:"varint,2,opt,name=truncate_to,json=truncateTo,proto3" json:"truncate_to,omitempty"`
	Data                 []byte         `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *LogRecord) Reset()         { *m = LogRecord{} }
func (m *LogRecord) String() string { return proto.CompactTextString(m) }
func (*LogRecord) ProtoMessage()    {}
func (*LogRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_6286842f97d51001, []int{0}
}

func (m *LogRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogRecord.Unmarshal(m, b)
}
func (m *LogRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogRecord.Marshal(b, m, deterministic)
}
func (m *LogRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogRecord.Merge(m, src)
}
func (m *LogRecord) XXX_Size() int {
	return xxx_messageInfo_LogRecord.Size(m)
}
func (m *LogRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_LogRecord.DiscardUnknown(m)
}

var xxx_messageInfo_LogRecord proto.InternalMessageInfo

func (m *LogRecord) GetType() LogRecord_Type {
	if m != nil {
		return m.Type
	}
	return LogRecord_ENTRY
}

func (m *LogRecord) GetTruncateTo() bool {
	if m != nil {
		return m.TruncateTo
	}
	return false
}

func (m *LogRecord) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("smartbftprotos.LogRecord_Type", LogRecord_Type_name, LogRecord_Type_value)
	proto.RegisterType((*LogRecord)(nil), "smartbftprotos.LogRecord")
}

func init() { proto.RegisterFile("logrecord.proto", fileDescriptor_6286842f97d51001) }

var fileDescriptor_6286842f97d51001 = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcf, 0xc9, 0x4f, 0x2f,
	0x4a, 0x4d, 0xce, 0x2f, 0x4a, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2b, 0xce, 0x4d,
	0x2c, 0x2a, 0x49, 0x4a, 0x2b, 0x01, 0x73, 0x8b, 0x95, 0x96, 0x30, 0x72, 0x71, 0xfa, 0xe4, 0xa7,
	0x07, 0x81, 0xd5, 0x08, 0x19, 0x71, 0xb1, 0x94, 0x54, 0x16, 0xa4, 0x4a, 0x30, 0x2a, 0x30, 0x6a,
	0xf0, 0x19, 0xc9, 0xe9, 0xa1, 0x2a, 0xd6, 0x83, 0x2b, 0xd4, 0x0b, 0xa9, 0x2c, 0x48, 0x0d, 0x02,
	0xab, 0x15, 0x92, 0xe7, 0xe2, 0x2e, 0x29, 0x2a, 0xcd, 0x4b, 0x4e, 0x2c, 0x49, 0x8d, 0x2f, 0xc9,
	0x97, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x08, 0xe2, 0x82, 0x09, 0x85, 0xe4, 0x0b, 0x09, 0x71, 0xb1,
	0xa4, 0x24, 0x96, 0x24, 0x4a, 0x30, 0x2b, 0x30, 0x6a, 0xf0, 0x04, 0x81, 0xd9, 0x4a, 0x7a, 0x5c,
	0x2c, 0x20, 0x23, 0x84, 0x38, 0xb9, 0x58, 0x5d, 0xfd, 0x42, 0x82, 0x22, 0x05, 0x18, 0x84, 0xb8,
	0xb9, 0xd8, 0x9d, 0xfd, 0xfd, 0x42, 0x82, 0xfc, 0x7d, 0x04, 0x18, 0x85, 0xf8, 0xb8, 0xb8, 0x9c,
	0x83, 0x9c, 0xe3, 0x1d, 0xfd, 0x9c, 0x3d, 0xfc, 0x83, 0x04, 0x98, 0x92, 0xd8, 0xc0, 0x2e, 0x30,
	0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xc2, 0xe0, 0x64, 0xdf, 0xd0, 0x00, 0x00, 0x00,
}
