// Code generated by protoc-gen-go. DO NOT EDIT.
// source: smartbftprotos/messages.proto

package smartbftprotos

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	// Types that are valid to be assigned to Content:
	//	*Message_PrePrepare
	//	*Message_Prepare
	//	*Message_Commit
	//	*Message_ViewChange
	//	*Message_ViewData
	//	*Message_NewView
	//	*Message_HeartBeat
	//	*Message_HeartBeatResponse
	//	*Message_StateTransferRequest
	//	*Message_StateTransferResponse
	Content              isMessage_Content `protobuf_oneof:"content"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d30f2fcdff47131, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

type isMessage_Content interface {
	isMessage_Content()
}

type Message_PrePrepare struct {
	PrePrepare *PrePrepare `protobuf:"bytes,1,opt,name=pre_prepare,json=prePrepare,proto3,oneof"`
}

type Message_Prepare struct {
	Prepare *Prepare `protobuf:"bytes,2,opt,name=prepare,proto3,oneof"`
}

type Message_Commit struct {
	Commit *Commit `protobuf:"bytes,3,opt,name=commit,proto3,oneof"`
}

type Message_ViewChange struct {
	ViewChange *ViewChange `protobuf:"bytes,4,opt,name=view_change,json=viewChange,proto3,oneof"`
}

type Message_ViewData struct {
	ViewData *SignedViewData `protobuf:"bytes,5,opt,name=view_data,json=viewData,proto3,oneof"`
}

type Message_NewView struct {
	NewView *NewView `protobuf:"bytes,6,opt,name=new_view,json=newView,proto3,oneof"`
}

type Message_HeartBeat struct {
	HeartBeat *HeartBeat `protobuf:"bytes,7,opt,name=heart_beat,json=heartBeat,proto3,oneof"`
}

type Message_HeartBeatResponse struct {
	HeartBeatResponse *HeartBeatResponse `protobuf:"bytes,8,opt,name=heart_beat_response,json=heartBeatResponse,proto3,oneof"`
}

type Message_StateTransferRequest struct {
	StateTransferRequest *StateTransferRequest `protobuf:"bytes,9,opt,name=state_transfer_request,json=stateTransferRequest,proto3,oneof"`
}

type Message_StateTransferResponse struct {
	StateTransferResponse *StateTransferResponse `protobuf:"bytes,10,opt,name=state_transfer_response,json=stateTransferResponse,proto3,oneof"`
}

func (*Message_PrePrepare) isMessage_Content() {}

func (*Message_Prepare) isMessage_Content() {}

func (*Message_Commit) isMessage_Content() {}

func (*Message_ViewChange) isMessage_Content() {}

func (*Message_ViewData) isMessage_Content() {}

func (*Message_NewView) isMessage_Content() {}

func (*Message_HeartBeat) isMessage_Content() {}

func (*Message_HeartBeatResponse) isMessage_Content() {}

func (*Message_StateTransferRequest) isMessage_Content() {}

func (*Message_StateTransferResponse) isMessage_Content() {}

func (m *Message) GetContent() isMessage_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Message) GetPrePrepare() *PrePrepare {
	if x, ok := m.GetContent().(*Message_PrePrepare); ok {
		return x.PrePrepare
	}
	return nil
}

func (m *Message) GetPrepare() *Prepare {
	if x, ok := m.GetContent().(*Message_Prepare); ok {
		return x.Prepare
	}
	return nil
}

func (m *Message) GetCommit() *Commit {
	if x, ok := m.GetContent().(*Message_Commit); ok {
		return x.Commit
	}
	return nil
}

func (m *Message) GetViewChange() *ViewChange {
	if x, ok := m.GetContent().(*Message_ViewChange); ok {
		return x.ViewChange
	}
	return nil
}

func (m *Message) GetViewData() *SignedViewData {
	if x, ok := m.GetContent().(*Message_ViewData); ok {
		return x.ViewData
	}
	return nil
}

func (m *Message) GetNewView() *NewView {
	if x, ok := m.GetContent().(*Message_NewView); ok {
		return x.NewView
	}
	return nil
}

func (m *Message) GetHeartBeat() *HeartBeat {
	if x, ok := m.GetContent().(*Message_HeartBeat); ok {
		return x.HeartBeat
	}
	return nil
}

func (m *Message) GetHeartBeatResponse() *HeartBeatResponse {
	if x, ok := m.GetContent().(*Message_HeartBeatResponse); ok {
		return x.HeartBeatResponse
	}
	return nil
}

func (m *Message) GetStateTransferRequest() *StateTransferRequest {
	if x, ok := m.GetContent().(*Message_StateTransferRequest); ok {
		return x.StateTransferRequest
	}
	return nil
}

func (m *Message) GetStateTransferResponse() *StateTransferResponse {
	if x, ok := m.GetContent().(*Message_StateTransferResponse); ok {
		return x.StateTransferResponse
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Message) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Message_PrePrepare)(nil),
		(*Message_Prepare)(nil),
		(*Message_Commit)(nil),
		(*Message_ViewChange)(nil),
		(*Message_ViewData)(nil),
		(*Message_NewView)(nil),
		(*Message_HeartBeat)(nil),
		(*Message_HeartBeatResponse)(nil),
		(*Message_StateTransferRequest)(nil),
		(*Message_StateTransferResponse)(nil),
	}
}

type PrePrepare struct {
	View                 uint64    `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	Seq                  uint64    `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Proposal             *Proposal `protobuf:"bytes,3,opt,name=proposal,proto3" json:"proposal,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PrePrepare) Reset()         { *m = PrePrepare{} }
func (m *PrePrepare) String() string { return proto.CompactTextString(m) }
func (*PrePrepare) ProtoMessage()    {}
func (*PrePrepare) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d30f2fcdff47131, []int{1}
}

func (m *PrePrepare) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrePrepare.Unmarshal(m, b)
}
func (m *PrePrepare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrePrepare.Marshal(b, m, deterministic)
}
func (m *PrePrepare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrePrepare.Merge(m, src)
}
func (m *PrePrepare) XXX_Size() int {
	return xxx_messageInfo_PrePrepare.Size(m)
}
func (m *PrePrepare) XXX_DiscardUnknown() {
	xxx_messageInfo_PrePrepare.DiscardUnknown(m)
}

var xxx_messageInfo_PrePrepare proto.InternalMessageInfo

func (m *PrePrepare) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *PrePrepare) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *PrePrepare) GetProposal() *Proposal {
	if m != nil {
		return m.Proposal
	}
	return nil
}

type Prepare struct {
	View                 uint64   `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	Seq                  uint64   `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Digest               string   `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	Assist               bool     `protobuf:"varint,4,opt,name=assist,proto3" json:"assist,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Prepare) Reset()         { *m = Prepare{} }
func (m *Prepare) String() string { return proto.CompactTextString(m) }
func (*Prepare) ProtoMessage()    {}
func (*Prepare) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d30f2fcdff47131, []int{2}
}

func (m *Prepare) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Prepare.Unmarshal(m, b)
}
func (m *Prepare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Prepare.Marshal(b, m, deterministic)
}
func (m *Prepare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Prepare.Merge(m, src)
}
func (m *Prepare) XXX_Size() int {
	return xxx_messageInfo_Prepare.Size(m)
}
func (m *Prepare) XXX_DiscardUnknown() {
	xxx_messageInfo_Prepare.DiscardUnknown(m)
}

var xxx_messageInfo_Prepare proto.InternalMessageInfo

func (m *Prepare) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *Prepare) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *Prepare) GetDigest() string {
	if m != nil {
		return m.Digest
	}
	return ""
}

func (m *Prepare) GetAssist() bool {
	if m != nil {
		return m.Assist
	}
	return false
}

type ProposedRecord struct {
	PrePrepare           *PrePrepare `protobuf:"bytes,1,opt,name=pre_prepare,json=prePrepare,proto3" json:"pre_prepare,omitempty"`
	Prepare              *Prepare    `protobuf:"bytes,2,opt,name=prepare,proto3" json:"prepare,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ProposedRecord) Reset()         { *m = ProposedRecord{} }
func (m *ProposedRecord) String() string { return proto.CompactTextString(m) }
func (*ProposedRecord) ProtoMessage()    {}
func (*ProposedRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d30f2fcdff47131, []int{3}
}

func (m *ProposedRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProposedRecord.Unmarshal(m, b)
}
func (m *ProposedRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProposedRecord.Marshal(b, m, deterministic)
}
func (m *ProposedRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProposedRecord.Merge(m, src)
}
func (m *ProposedRecord) XXX_Size() int {
	return xxx_messageInfo_ProposedRecord.Size(m)
}
func (m *ProposedRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_ProposedRecord.DiscardUnknown(m)
}

var xxx_messageInfo_ProposedRecord proto.InternalMessageInfo

func (m *ProposedRecord) GetPrePrepare() *PrePrepare {
	if m != nil {
		return m.PrePrepare
	}
	return nil
}

func (m *ProposedRecord) GetPrepare() *Prepare {
	if m != nil {
		return m.Prepare
	}
	return nil
}

type Commit struct {
	View                 uint64     `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	Seq                  uint64     `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Digest               string     `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	Signature            *Signature `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	Assist               bool       `protobuf:"varint,5,opt,name=assist,proto3" json:"assist,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Commit) Reset()         { *m = Commit{} }
func (m *Commit) String() string { return proto.CompactTextString(m) }
func (*Commit) ProtoMessage()    {}
func (*Commit) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d30f2fcdff47131, []int{4}
}

func (m *Commit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Commit.Unmarshal(m, b)
}
func (m *Commit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Commit.Marshal(b, m, deterministic)
}
func (m *Commit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Commit.Merge(m, src)
}
func (m *Commit) XXX_Size() int {
	return xxx_messageInfo_Commit.Size(m)
}
func (m *Commit) XXX_DiscardUnknown() {
	xxx_messageInfo_Commit.DiscardUnknown(m)
}

var xxx_messageInfo_Commit proto.InternalMessageInfo

func (m *Commit) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *Commit) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *Commit) GetDigest() string {
	if m != nil {
		return m.Digest
	}
	return ""
}

func (m *Commit) GetSignature() *Signature {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Commit) GetAssist() bool {
	if m != nil {
		return m.Assist
	}
	return false
}

type ViewChange struct {
	NextView             uint64   `protobuf:"varint,1,opt,name=next_view,json=nextView,proto3" json:"next_view,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ViewChange) Reset()         { *m = ViewChange{} }
func (m *ViewChange) String() string { return proto.CompactTextString(m) }
func (*ViewChange) ProtoMessage()    {}
func (*ViewChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d30f2fcdff47131, []int{5}
}

func (m *ViewChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewChange.Unmarshal(m, b)
}
func (m *ViewChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewChange.Marshal(b, m, deterministic)
}
func (m *ViewChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewChange.Merge(m, src)
}
func (m *ViewChange) XXX_Size() int {
	return xxx_messageInfo_ViewChange.Size(m)
}
func (m *ViewChange) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewChange.DiscardUnknown(m)
}

var xxx_messageInfo_ViewChange proto.InternalMessageInfo

func (m *ViewChange) GetNextView() uint64 {
	if m != nil {
		return m.NextView
	}
	return 0
}

func (m *ViewChange) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type ViewData struct {
	NextView               uint64       `protobuf:"varint,1,opt,name=next_view,json=nextView,proto3" json:"next_view,omitempty"`
	LastDecision           *Proposal    `protobuf:"bytes,2,opt,name=last_decision,json=lastDecision,proto3" json:"last_decision,omitempty"`
	LastDecisionSignatures []*Signature `protobuf:"bytes,3,rep,name=last_decision_signatures,json=lastDecisionSignatures,proto3" json:"last_decision_signatures,omitempty"`
	InFlightProposal       *Proposal    `protobuf:"bytes,4,opt,name=in_flight_proposal,json=inFlightProposal,proto3" json:"in_flight_proposal,omitempty"`
	InFlightPrepared       bool         `protobuf:"varint,5,opt,name=in_flight_prepared,json=inFlightPrepared,proto3" json:"in_flight_prepared,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}     `json:"-"`
	XXX_unrecognized       []byte       `json:"-"`
	XXX_sizecache          int32        `json:"-"`
}

func (m *ViewData) Reset()         { *m = ViewData{} }
func (m *ViewData) String() string { return proto.CompactTextString(m) }
func (*ViewData) ProtoMessage()    {}
func (*ViewData) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d30f2fcdff47131, []int{6}
}

func (m *ViewData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewData.Unmarshal(m, b)
}
func (m *ViewData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewData.Marshal(b, m, deterministic)
}
func (m *ViewData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewData.Merge(m, src)
}
func (m *ViewData) XXX_Size() int {
	return xxx_messageInfo_ViewData.Size(m)
}
func (m *ViewData) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewData.DiscardUnknown(m)
}

var xxx_messageInfo_ViewData proto.InternalMessageInfo

func (m *ViewData) GetNextView() uint64 {
	if m != nil {
		return m.NextView
	}
	return 0
}

func (m *ViewData) GetLastDecision() *Proposal {
	if m != nil {
		return m.LastDecision
	}
	return nil
}

func (m *ViewData) GetLastDecisionSignatures() []*Signature {
	if m != nil {
		return m.LastDecisionSignatures
	}
	return nil
}

func (m *ViewData) GetInFlightProposal() *Proposal {
	if m != nil {
		return m.InFlightProposal
	}
	return nil
}

func (m *ViewData) GetInFlightPrepared() bool {
	if m != nil {
		return m.InFlightPrepared
	}
	return false
}

type SignedViewData struct {
	RawViewData          []byte   `protobuf:"bytes,1,opt,name=raw_view_data,json=rawViewData,proto3" json:"raw_view_data,omitempty"`
	Signer               uint64   `protobuf:"varint,2,opt,name=signer,proto3" json:"signer,omitempty"`
	Signature            []byte   `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignedViewData) Reset()         { *m = SignedViewData{} }
func (m *SignedViewData) String() string { return proto.CompactTextString(m) }
func (*SignedViewData) ProtoMessage()    {}
func (*SignedViewData) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d30f2fcdff47131, []int{7}
}

func (m *SignedViewData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedViewData.Unmarshal(m, b)
}
func (m *SignedViewData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedViewData.Marshal(b, m, deterministic)
}
func (m *SignedViewData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedViewData.Merge(m, src)
}
func (m *SignedViewData) XXX_Size() int {
	return xxx_messageInfo_SignedViewData.Size(m)
}
func (m *SignedViewData) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedViewData.DiscardUnknown(m)
}

var xxx_messageInfo_SignedViewData proto.InternalMessageInfo

func (m *SignedViewData) GetRawViewData() []byte {
	if m != nil {
		return m.RawViewData
	}
	return nil
}

func (m *SignedViewData) GetSigner() uint64 {
	if m != nil {
		return m.Signer
	}
	return 0
}

func (m *SignedViewData) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type NewView struct {
	SignedViewData       []*SignedViewData `protobuf:"bytes,2,rep,name=signed_view_data,json=signedViewData,proto3" json:"signed_view_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *NewView) Reset()         { *m = NewView{} }
func (m *NewView) String() string { return proto.CompactTextString(m) }
func (*NewView) ProtoMessage()    {}
func (*NewView) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d30f2fcdff47131, []int{8}
}

func (m *NewView) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewView.Unmarshal(m, b)
}
func (m *NewView) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewView.Marshal(b, m, deterministic)
}
func (m *NewView) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewView.Merge(m, src)
}
func (m *NewView) XXX_Size() int {
	return xxx_messageInfo_NewView.Size(m)
}
func (m *NewView) XXX_DiscardUnknown() {
	xxx_messageInfo_NewView.DiscardUnknown(m)
}

var xxx_messageInfo_NewView proto.InternalMessageInfo

func (m *NewView) GetSignedViewData() []*SignedViewData {
	if m != nil {
		return m.SignedViewData
	}
	return nil
}

type HeartBeat struct {
	View                 uint64   `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	Seq                  uint64   `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartBeat) Reset()         { *m = HeartBeat{} }
func (m *HeartBeat) String() string { return proto.CompactTextString(m) }
func (*HeartBeat) ProtoMessage()    {}
func (*HeartBeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d30f2fcdff47131, []int{9}
}

func (m *HeartBeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartBeat.Unmarshal(m, b)
}
func (m *HeartBeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartBeat.Marshal(b, m, deterministic)
}
func (m *HeartBeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartBeat.Merge(m, src)
}
func (m *HeartBeat) XXX_Size() int {
	return xxx_messageInfo_HeartBeat.Size(m)
}
func (m *HeartBeat) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartBeat.DiscardUnknown(m)
}

var xxx_messageInfo_HeartBeat proto.InternalMessageInfo

func (m *HeartBeat) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *HeartBeat) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

type HeartBeatResponse struct {
	View                 uint64   `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartBeatResponse) Reset()         { *m = HeartBeatResponse{} }
func (m *HeartBeatResponse) String() string { return proto.CompactTextString(m) }
func (*HeartBeatResponse) ProtoMessage()    {}
func (*HeartBeatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d30f2fcdff47131, []int{10}
}

func (m *HeartBeatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartBeatResponse.Unmarshal(m, b)
}
func (m *HeartBeatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartBeatResponse.Marshal(b, m, deterministic)
}
func (m *HeartBeatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartBeatResponse.Merge(m, src)
}
func (m *HeartBeatResponse) XXX_Size() int {
	return xxx_messageInfo_HeartBeatResponse.Size(m)
}
func (m *HeartBeatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartBeatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HeartBeatResponse proto.InternalMessageInfo

func (m *HeartBeatResponse) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

type Signature struct {
	Signer               uint64   `protobuf:"varint,1,opt,name=signer,proto3" json:"signer,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Msg                  []byte   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Signature) Reset()         { *m = Signature{} }
func (m *Signature) String() string { return proto.CompactTextString(m) }
func (*Signature) ProtoMessage()    {}
func (*Signature) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d30f2fcdff47131, []int{11}
}

func (m *Signature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Signature.Unmarshal(m, b)
}
func (m *Signature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Signature.Marshal(b, m, deterministic)
}
func (m *Signature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Signature.Merge(m, src)
}
func (m *Signature) XXX_Size() int {
	return xxx_messageInfo_Signature.Size(m)
}
func (m *Signature) XXX_DiscardUnknown() {
	xxx_messageInfo_Signature.DiscardUnknown(m)
}

var xxx_messageInfo_Signature proto.InternalMessageInfo

func (m *Signature) GetSigner() uint64 {
	if m != nil {
		return m.Signer
	}
	return 0
}

func (m *Signature) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Signature) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

type Proposal struct {
	Header               []byte   `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Payload              []byte   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Metadata             []byte   `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	VerificationSequence uint64   `protobuf:"varint,4,opt,name=verification_sequence,json=verificationSequence,proto3" json:"verification_sequence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Proposal) Reset()         { *m = Proposal{} }
func (m *Proposal) String() string { return proto.CompactTextString(m) }
func (*Proposal) ProtoMessage()    {}
func (*Proposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d30f2fcdff47131, []int{12}
}

func (m *Proposal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Proposal.Unmarshal(m, b)
}
func (m *Proposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Proposal.Marshal(b, m, deterministic)
}
func (m *Proposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proposal.Merge(m, src)
}
func (m *Proposal) XXX_Size() int {
	return xxx_messageInfo_Proposal.Size(m)
}
func (m *Proposal) XXX_DiscardUnknown() {
	xxx_messageInfo_Proposal.DiscardUnknown(m)
}

var xxx_messageInfo_Proposal proto.InternalMessageInfo

func (m *Proposal) GetHeader() []byte {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Proposal) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Proposal) GetMetadata() []byte {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Proposal) GetVerificationSequence() uint64 {
	if m != nil {
		return m.VerificationSequence
	}
	return 0
}

type ViewMetadata struct {
	ViewId               uint64   `protobuf:"varint,1,opt,name=view_id,json=viewId,proto3" json:"view_id,omitempty"`
	LatestSequence       uint64   `protobuf:"varint,2,opt,name=latest_sequence,json=latestSequence,proto3" json:"latest_sequence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ViewMetadata) Reset()         { *m = ViewMetadata{} }
func (m *ViewMetadata) String() string { return proto.CompactTextString(m) }
func (*ViewMetadata) ProtoMessage()    {}
func (*ViewMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d30f2fcdff47131, []int{13}
}

func (m *ViewMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewMetadata.Unmarshal(m, b)
}
func (m *ViewMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewMetadata.Marshal(b, m, deterministic)
}
func (m *ViewMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewMetadata.Merge(m, src)
}
func (m *ViewMetadata) XXX_Size() int {
	return xxx_messageInfo_ViewMetadata.Size(m)
}
func (m *ViewMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ViewMetadata proto.InternalMessageInfo

func (m *ViewMetadata) GetViewId() uint64 {
	if m != nil {
		return m.ViewId
	}
	return 0
}

func (m *ViewMetadata) GetLatestSequence() uint64 {
	if m != nil {
		return m.LatestSequence
	}
	return 0
}

type SavedMessage struct {
	// Types that are valid to be assigned to Content:
	//	*SavedMessage_ProposedRecord
	//	*SavedMessage_Commit
	//	*SavedMessage_NewView
	//	*SavedMessage_ViewChange
	Content              isSavedMessage_Content `protobuf_oneof:"content"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SavedMessage) Reset()         { *m = SavedMessage{} }
func (m *SavedMessage) String() string { return proto.CompactTextString(m) }
func (*SavedMessage) ProtoMessage()    {}
func (*SavedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d30f2fcdff47131, []int{14}
}

func (m *SavedMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SavedMessage.Unmarshal(m, b)
}
func (m *SavedMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SavedMessage.Marshal(b, m, deterministic)
}
func (m *SavedMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SavedMessage.Merge(m, src)
}
func (m *SavedMessage) XXX_Size() int {
	return xxx_messageInfo_SavedMessage.Size(m)
}
func (m *SavedMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SavedMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SavedMessage proto.InternalMessageInfo

type isSavedMessage_Content interface {
	isSavedMessage_Content()
}

type SavedMessage_ProposedRecord struct {
	ProposedRecord *ProposedRecord `protobuf:"bytes,1,opt,name=proposed_record,json=proposedRecord,proto3,oneof"`
}

type SavedMessage_Commit struct {
	Commit *Message `protobuf:"bytes,2,opt,name=commit,proto3,oneof"`
}

type SavedMessage_NewView struct {
	NewView *ViewMetadata `protobuf:"bytes,3,opt,name=new_view,json=newView,proto3,oneof"`
}

type SavedMessage_ViewChange struct {
	ViewChange *ViewChange `protobuf:"bytes,4,opt,name=view_change,json=viewChange,proto3,oneof"`
}

func (*SavedMessage_ProposedRecord) isSavedMessage_Content() {}

func (*SavedMessage_Commit) isSavedMessage_Content() {}

func (*SavedMessage_NewView) isSavedMessage_Content() {}

func (*SavedMessage_ViewChange) isSavedMessage_Content() {}

func (m *SavedMessage) GetContent() isSavedMessage_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *SavedMessage) GetProposedRecord() *ProposedRecord {
	if x, ok := m.GetContent().(*SavedMessage_ProposedRecord); ok {
		return x.ProposedRecord
	}
	return nil
}

func (m *SavedMessage) GetCommit() *Message {
	if x, ok := m.GetContent().(*SavedMessage_Commit); ok {
		return x.Commit
	}
	return nil
}

func (m *SavedMessage) GetNewView() *ViewMetadata {
	if x, ok := m.GetContent().(*SavedMessage_NewView); ok {
		return x.NewView
	}
	return nil
}

func (m *SavedMessage) GetViewChange() *ViewChange {
	if x, ok := m.GetContent().(*SavedMessage_ViewChange); ok {
		return x.ViewChange
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SavedMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SavedMessage_ProposedRecord)(nil),
		(*SavedMessage_Commit)(nil),
		(*SavedMessage_NewView)(nil),
		(*SavedMessage_ViewChange)(nil),
	}
}

type StateTransferRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StateTransferRequest) Reset()         { *m = StateTransferRequest{} }
func (m *StateTransferRequest) String() string { return proto.CompactTextString(m) }
func (*StateTransferRequest) ProtoMessage()    {}
func (*StateTransferRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d30f2fcdff47131, []int{15}
}

func (m *StateTransferRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateTransferRequest.Unmarshal(m, b)
}
func (m *StateTransferRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateTransferRequest.Marshal(b, m, deterministic)
}
func (m *StateTransferRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateTransferRequest.Merge(m, src)
}
func (m *StateTransferRequest) XXX_Size() int {
	return xxx_messageInfo_StateTransferRequest.Size(m)
}
func (m *StateTransferRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StateTransferRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StateTransferRequest proto.InternalMessageInfo

type StateTransferResponse struct {
	ViewNum              uint64   `protobuf:"varint,1,opt,name=view_num,json=viewNum,proto3" json:"view_num,omitempty"`
	Sequence             uint64   `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StateTransferResponse) Reset()         { *m = StateTransferResponse{} }
func (m *StateTransferResponse) String() string { return proto.CompactTextString(m) }
func (*StateTransferResponse) ProtoMessage()    {}
func (*StateTransferResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d30f2fcdff47131, []int{16}
}

func (m *StateTransferResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateTransferResponse.Unmarshal(m, b)
}
func (m *StateTransferResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateTransferResponse.Marshal(b, m, deterministic)
}
func (m *StateTransferResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateTransferResponse.Merge(m, src)
}
func (m *StateTransferResponse) XXX_Size() int {
	return xxx_messageInfo_StateTransferResponse.Size(m)
}
func (m *StateTransferResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StateTransferResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StateTransferResponse proto.InternalMessageInfo

func (m *StateTransferResponse) GetViewNum() uint64 {
	if m != nil {
		return m.ViewNum
	}
	return 0
}

func (m *StateTransferResponse) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func init() {
	proto.RegisterType((*Message)(nil), "smartbftprotos.Message")
	proto.RegisterType((*PrePrepare)(nil), "smartbftprotos.PrePrepare")
	proto.RegisterType((*Prepare)(nil), "smartbftprotos.Prepare")
	proto.RegisterType((*ProposedRecord)(nil), "smartbftprotos.ProposedRecord")
	proto.RegisterType((*Commit)(nil), "smartbftprotos.Commit")
	proto.RegisterType((*ViewChange)(nil), "smartbftprotos.ViewChange")
	proto.RegisterType((*ViewData)(nil), "smartbftprotos.ViewData")
	proto.RegisterType((*SignedViewData)(nil), "smartbftprotos.SignedViewData")
	proto.RegisterType((*NewView)(nil), "smartbftprotos.NewView")
	proto.RegisterType((*HeartBeat)(nil), "smartbftprotos.HeartBeat")
	proto.RegisterType((*HeartBeatResponse)(nil), "smartbftprotos.HeartBeatResponse")
	proto.RegisterType((*Signature)(nil), "smartbftprotos.Signature")
	proto.RegisterType((*Proposal)(nil), "smartbftprotos.Proposal")
	proto.RegisterType((*ViewMetadata)(nil), "smartbftprotos.ViewMetadata")
	proto.RegisterType((*SavedMessage)(nil), "smartbftprotos.SavedMessage")
	proto.RegisterType((*StateTransferRequest)(nil), "smartbftprotos.StateTransferRequest")
	proto.RegisterType((*StateTransferResponse)(nil), "smartbftprotos.StateTransferResponse")
}

func init() {
	proto.RegisterFile("smartbftprotos/messages.proto", fileDescriptor_0d30f2fcdff47131)
}

var fileDescriptor_0d30f2fcdff47131 = []byte{
	// 934 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0x5f, 0x6f, 0x1b, 0x45,
	0x10, 0xb7, 0x63, 0xc7, 0xf6, 0x4d, 0x5c, 0x37, 0x5d, 0x12, 0xe7, 0x52, 0x4a, 0x55, 0x4e, 0xa0,
	0xf2, 0x80, 0x02, 0x21, 0x48, 0x08, 0x50, 0x1e, 0x68, 0xab, 0xca, 0x15, 0x6a, 0x14, 0xad, 0x11,
	0x4f, 0x48, 0xab, 0x8d, 0x6f, 0x62, 0x1f, 0xf2, 0xfd, 0xe9, 0xee, 0xda, 0x86, 0x37, 0xbe, 0x00,
	0x0f, 0x3c, 0xf1, 0x39, 0xf8, 0x02, 0x7c, 0xb6, 0x6a, 0xff, 0xdc, 0xf9, 0xce, 0xbe, 0x26, 0xad,
	0xf2, 0xb6, 0x33, 0x3b, 0xbf, 0xdf, 0xce, 0xcc, 0xce, 0xcc, 0x2e, 0x7c, 0x22, 0x63, 0x2e, 0xd4,
	0xd5, 0xb5, 0xca, 0x44, 0xaa, 0x52, 0xf9, 0x55, 0x8c, 0x52, 0xf2, 0x29, 0xca, 0x13, 0x23, 0x93,
	0x41, 0x75, 0x3b, 0xf8, 0x7f, 0x17, 0xba, 0xaf, 0xad, 0x09, 0x39, 0x87, 0xbd, 0x4c, 0x20, 0xcb,
	0x04, 0x66, 0x5c, 0xa0, 0xdf, 0x7c, 0xd2, 0xfc, 0x62, 0xef, 0x9b, 0x87, 0x27, 0x55, 0xc4, 0xc9,
	0xa5, 0xc0, 0x4b, 0x6b, 0x31, 0x6a, 0x50, 0xc8, 0x0a, 0x89, 0x9c, 0x41, 0x37, 0x87, 0xee, 0x18,
	0xe8, 0x51, 0x0d, 0xd4, 0xe1, 0x72, 0x4b, 0xf2, 0x35, 0x74, 0x26, 0x69, 0x1c, 0x47, 0xca, 0x6f,
	0x19, 0xcc, 0x70, 0x13, 0xf3, 0xdc, 0xec, 0x8e, 0x1a, 0xd4, 0xd9, 0x69, 0x2f, 0x97, 0x11, 0xae,
	0xd8, 0x64, 0xc6, 0x93, 0x29, 0xfa, 0xed, 0x7a, 0x2f, 0x7f, 0x8d, 0x70, 0xf5, 0xdc, 0x58, 0x68,
	0x2f, 0x97, 0x85, 0x44, 0xce, 0xc1, 0x33, 0xf0, 0x90, 0x2b, 0xee, 0xef, 0x1a, 0xf0, 0xe3, 0x4d,
	0xf0, 0x38, 0x9a, 0x26, 0x18, 0x6a, 0x8a, 0x17, 0x5c, 0xf1, 0x51, 0x83, 0xf6, 0x96, 0x6e, 0x4d,
	0xbe, 0x85, 0x5e, 0x82, 0x2b, 0xa6, 0x65, 0xbf, 0x53, 0x1f, 0xe5, 0x05, 0xae, 0x34, 0x54, 0x47,
	0x99, 0xd8, 0x25, 0xf9, 0x01, 0x60, 0x86, 0x5c, 0x28, 0x76, 0x85, 0x5c, 0xf9, 0x5d, 0x83, 0x3b,
	0xde, 0xc4, 0x8d, 0xb4, 0xc5, 0x33, 0xe4, 0x3a, 0x58, 0x6f, 0x96, 0x0b, 0x64, 0x0c, 0x1f, 0xad,
	0xb1, 0x4c, 0xa0, 0xcc, 0xd2, 0x44, 0xa2, 0xdf, 0x33, 0x24, 0x9f, 0xbe, 0x93, 0x84, 0x3a, 0xc3,
	0x51, 0x83, 0x3e, 0x98, 0x6d, 0x2a, 0xc9, 0x6f, 0x30, 0x94, 0x8a, 0x2b, 0x64, 0x4a, 0xf0, 0x44,
	0x5e, 0xa3, 0x60, 0x02, 0xdf, 0x2c, 0x50, 0x2a, 0xdf, 0x33, 0xbc, 0x9f, 0x6d, 0xa5, 0x44, 0x5b,
	0xff, 0xe2, 0x8c, 0xa9, 0xb5, 0x1d, 0x35, 0xe8, 0x81, 0xac, 0xd1, 0x13, 0x06, 0x47, 0x5b, 0xec,
	0xce, 0x6d, 0x30, 0xf4, 0x9f, 0xdf, 0x42, 0x5f, 0xb8, 0x7e, 0x28, 0xeb, 0x36, 0x9e, 0x79, 0xd0,
	0x9d, 0xa4, 0x89, 0xc2, 0x44, 0x05, 0x33, 0x80, 0x75, 0x45, 0x12, 0x02, 0x6d, 0x73, 0x35, 0xba,
	0x76, 0xdb, 0xd4, 0xac, 0xc9, 0x3e, 0xb4, 0x24, 0xbe, 0x31, 0x35, 0xd9, 0xa6, 0x7a, 0xa9, 0x2f,
	0x31, 0x13, 0x69, 0x96, 0x4a, 0x3e, 0x77, 0x65, 0xe7, 0x6f, 0x97, 0xaa, 0xdd, 0xa7, 0x85, 0x65,
	0xc0, 0xa0, 0xfb, 0x61, 0xc7, 0x0c, 0xa1, 0x13, 0x46, 0x53, 0x9d, 0x54, 0x7d, 0x88, 0x47, 0x9d,
	0xa4, 0xf5, 0x5c, 0xca, 0x48, 0x2a, 0x53, 0xbc, 0x3d, 0xea, 0xa4, 0xe0, 0xaf, 0x26, 0x0c, 0xec,
	0xb9, 0x18, 0x52, 0x9c, 0xa4, 0x22, 0x24, 0x3f, 0x7e, 0x60, 0x4b, 0x56, 0x1a, 0xf2, 0xf4, 0x7d,
	0x1b, 0xb2, 0x68, 0xc7, 0xe0, 0xdf, 0x26, 0x74, 0x6c, 0xc7, 0xdd, 0x31, 0xc6, 0xef, 0xc0, 0x93,
	0xd1, 0x34, 0xe1, 0x6a, 0x21, 0xf2, 0x1e, 0x3d, 0xae, 0x6b, 0x33, 0x63, 0x40, 0xd7, 0xb6, 0xa5,
	0xe4, 0xec, 0x56, 0x92, 0xf3, 0x13, 0xc0, 0xba, 0xa7, 0xc9, 0xc7, 0xe0, 0x25, 0xf8, 0x87, 0x62,
	0x25, 0x0f, 0x7b, 0x5a, 0x61, 0xba, 0x6d, 0x08, 0x1d, 0x81, 0x5c, 0xa6, 0x89, 0x71, 0xd4, 0xa3,
	0x4e, 0x0a, 0xfe, 0xdb, 0x81, 0x5e, 0xde, 0xd4, 0x37, 0x33, 0x9c, 0xc3, 0xbd, 0x39, 0x97, 0x8a,
	0x85, 0x38, 0x89, 0x64, 0xe4, 0x88, 0x6e, 0xaa, 0x92, 0xbe, 0x36, 0x7f, 0xe1, 0xac, 0xc9, 0x18,
	0xfc, 0x0a, 0x9c, 0x15, 0xe1, 0x49, 0xbf, 0xf5, 0xa4, 0x75, 0x73, 0x2e, 0x86, 0x65, 0xaa, 0x42,
	0x2d, 0xc9, 0x4b, 0x20, 0x51, 0xc2, 0xae, 0xe7, 0xd1, 0x74, 0xa6, 0x58, 0x51, 0xbe, 0xed, 0x5b,
	0x1c, 0xdb, 0x8f, 0x92, 0x97, 0x06, 0x92, 0x6b, 0xc8, 0x97, 0x55, 0x1e, 0x73, 0xef, 0xa1, 0x4b,
	0x76, 0xc9, 0xda, 0xea, 0x83, 0xdf, 0x61, 0x50, 0x9d, 0x86, 0x24, 0x80, 0x7b, 0x82, 0xdb, 0x09,
	0x68, 0x87, 0xa8, 0x4e, 0x5e, 0x9f, 0xee, 0x09, 0xbe, 0x2a, 0x6c, 0x86, 0xd0, 0xd1, 0x21, 0xa3,
	0x70, 0xa5, 0xe2, 0x24, 0xf2, 0xa8, 0x5c, 0x15, 0x2d, 0x83, 0x5b, 0x2b, 0x82, 0x31, 0x74, 0xdd,
	0xec, 0x24, 0x23, 0xd8, 0x37, 0x90, 0xb0, 0x74, 0xce, 0x8e, 0xc9, 0xdc, 0x2d, 0xc3, 0x9a, 0x0e,
	0x64, 0x45, 0x0e, 0x4e, 0xc1, 0x2b, 0x66, 0xe2, 0xfb, 0xd5, 0x74, 0xf0, 0x14, 0x1e, 0x6c, 0x8d,
	0xd1, 0x3a, 0x68, 0xf0, 0x33, 0x78, 0xe3, 0x72, 0xe1, 0xba, 0x98, 0x9b, 0x95, 0x98, 0x0f, 0x60,
	0x77, 0xc9, 0xe7, 0x0b, 0xdb, 0x83, 0x7d, 0x6a, 0x05, 0x7d, 0x6a, 0x2c, 0xa7, 0x2e, 0x07, 0x7a,
	0x19, 0xfc, 0xdd, 0x84, 0x5e, 0x71, 0x49, 0x43, 0xe8, 0xcc, 0x90, 0x87, 0x8e, 0xac, 0x4f, 0x9d,
	0x44, 0x7c, 0xe8, 0x66, 0xfc, 0xcf, 0x79, 0xca, 0x43, 0x47, 0x97, 0x8b, 0xe4, 0x21, 0xf4, 0x62,
	0x54, 0xdc, 0x64, 0xca, 0xb2, 0x16, 0x32, 0x39, 0x83, 0xc3, 0x25, 0x8a, 0xe8, 0x3a, 0x9a, 0x70,
	0x65, 0xca, 0x51, 0xcf, 0xe9, 0x64, 0x62, 0x1b, 0xb3, 0x4d, 0x0f, 0xca, 0x9b, 0x63, 0xb7, 0x17,
	0x5c, 0x42, 0x5f, 0x27, 0xf1, 0x75, 0x4e, 0x72, 0x04, 0x5d, 0x73, 0x17, 0x51, 0x98, 0x07, 0xa8,
	0xc5, 0x57, 0x21, 0x79, 0x0a, 0xf7, 0xe7, 0x5c, 0xa1, 0x54, 0x6b, 0x5e, 0x9b, 0xcc, 0x81, 0x55,
	0x17, 0x8c, 0xff, 0xec, 0x40, 0x7f, 0xcc, 0x97, 0x18, 0xe6, 0x1f, 0x8e, 0x57, 0x70, 0x3f, 0x73,
	0xf3, 0x8e, 0x09, 0x33, 0xf0, 0xdc, 0x84, 0x7b, 0x5c, 0x5f, 0xcf, 0xf9, 0x58, 0x1c, 0x35, 0xe8,
	0x20, 0xab, 0x0e, 0xca, 0xd3, 0xe2, 0x1f, 0xf1, 0x8e, 0x51, 0xe7, 0xce, 0x2c, 0x7d, 0x24, 0xbe,
	0x2f, 0x3d, 0xe5, 0xf6, 0x15, 0x78, 0x54, 0xf7, 0x8b, 0xc8, 0x13, 0x50, 0x7e, 0xcf, 0xef, 0xf6,
	0x07, 0x29, 0x3f, 0x5f, 0x43, 0x38, 0xa8, 0x7b, 0x5a, 0x83, 0x0b, 0x38, 0xac, 0x7d, 0x13, 0xc9,
	0x31, 0x98, 0xcf, 0x08, 0x4b, 0x16, 0xb1, 0xbb, 0x07, 0x73, 0x2d, 0x17, 0x8b, 0x58, 0x97, 0xc0,
	0xc6, 0x0d, 0x14, 0xf2, 0x55, 0xc7, 0xf8, 0x74, 0xf6, 0x36, 0x00, 0x00, 0xff, 0xff, 0xd3, 0x8f,
	0xd7, 0x95, 0x1f, 0x0a, 0x00, 0x00,
}
