// Code generated by protoc-gen-go. DO NOT EDIT.
// source: smartbftprotos/messages.proto

package smartbftprotos

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	// Types that are valid to be assigned to Content:
	//	*Message_PrePrepare
	//	*Message_Prepare
	//	*Message_Commit
	//	*Message_Error
	//	*Message_ViewChange
	//	*Message_ViewData
	//	*Message_NewView
	//	*Message_HeartBeat
	Content              isMessage_Content `protobuf_oneof:"content"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d30f2fcdff47131, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

type isMessage_Content interface {
	isMessage_Content()
}

type Message_PrePrepare struct {
	PrePrepare *PrePrepare `protobuf:"bytes,1,opt,name=pre_prepare,json=prePrepare,proto3,oneof"`
}

type Message_Prepare struct {
	Prepare *Prepare `protobuf:"bytes,2,opt,name=prepare,proto3,oneof"`
}

type Message_Commit struct {
	Commit *Commit `protobuf:"bytes,3,opt,name=commit,proto3,oneof"`
}

type Message_Error struct {
	Error *Error `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

type Message_ViewChange struct {
	ViewChange *ViewChange `protobuf:"bytes,5,opt,name=view_change,json=viewChange,proto3,oneof"`
}

type Message_ViewData struct {
	ViewData *SignedViewData `protobuf:"bytes,6,opt,name=view_data,json=viewData,proto3,oneof"`
}

type Message_NewView struct {
	NewView *NewView `protobuf:"bytes,7,opt,name=new_view,json=newView,proto3,oneof"`
}

type Message_HeartBeat struct {
	HeartBeat *HeartBeat `protobuf:"bytes,8,opt,name=heart_beat,json=heartBeat,proto3,oneof"`
}

func (*Message_PrePrepare) isMessage_Content() {}

func (*Message_Prepare) isMessage_Content() {}

func (*Message_Commit) isMessage_Content() {}

func (*Message_Error) isMessage_Content() {}

func (*Message_ViewChange) isMessage_Content() {}

func (*Message_ViewData) isMessage_Content() {}

func (*Message_NewView) isMessage_Content() {}

func (*Message_HeartBeat) isMessage_Content() {}

func (m *Message) GetContent() isMessage_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Message) GetPrePrepare() *PrePrepare {
	if x, ok := m.GetContent().(*Message_PrePrepare); ok {
		return x.PrePrepare
	}
	return nil
}

func (m *Message) GetPrepare() *Prepare {
	if x, ok := m.GetContent().(*Message_Prepare); ok {
		return x.Prepare
	}
	return nil
}

func (m *Message) GetCommit() *Commit {
	if x, ok := m.GetContent().(*Message_Commit); ok {
		return x.Commit
	}
	return nil
}

func (m *Message) GetError() *Error {
	if x, ok := m.GetContent().(*Message_Error); ok {
		return x.Error
	}
	return nil
}

func (m *Message) GetViewChange() *ViewChange {
	if x, ok := m.GetContent().(*Message_ViewChange); ok {
		return x.ViewChange
	}
	return nil
}

func (m *Message) GetViewData() *SignedViewData {
	if x, ok := m.GetContent().(*Message_ViewData); ok {
		return x.ViewData
	}
	return nil
}

func (m *Message) GetNewView() *NewView {
	if x, ok := m.GetContent().(*Message_NewView); ok {
		return x.NewView
	}
	return nil
}

func (m *Message) GetHeartBeat() *HeartBeat {
	if x, ok := m.GetContent().(*Message_HeartBeat); ok {
		return x.HeartBeat
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Message) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Message_PrePrepare)(nil),
		(*Message_Prepare)(nil),
		(*Message_Commit)(nil),
		(*Message_Error)(nil),
		(*Message_ViewChange)(nil),
		(*Message_ViewData)(nil),
		(*Message_NewView)(nil),
		(*Message_HeartBeat)(nil),
	}
}

type PrePrepare struct {
	View                 uint64    `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	Seq                  uint64    `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Proposal             *Proposal `protobuf:"bytes,3,opt,name=proposal,proto3" json:"proposal,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PrePrepare) Reset()         { *m = PrePrepare{} }
func (m *PrePrepare) String() string { return proto.CompactTextString(m) }
func (*PrePrepare) ProtoMessage()    {}
func (*PrePrepare) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d30f2fcdff47131, []int{1}
}

func (m *PrePrepare) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrePrepare.Unmarshal(m, b)
}
func (m *PrePrepare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrePrepare.Marshal(b, m, deterministic)
}
func (m *PrePrepare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrePrepare.Merge(m, src)
}
func (m *PrePrepare) XXX_Size() int {
	return xxx_messageInfo_PrePrepare.Size(m)
}
func (m *PrePrepare) XXX_DiscardUnknown() {
	xxx_messageInfo_PrePrepare.DiscardUnknown(m)
}

var xxx_messageInfo_PrePrepare proto.InternalMessageInfo

func (m *PrePrepare) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *PrePrepare) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *PrePrepare) GetProposal() *Proposal {
	if m != nil {
		return m.Proposal
	}
	return nil
}

type Prepare struct {
	View                 uint64   `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	Seq                  uint64   `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Digest               string   `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	Assist               bool     `protobuf:"varint,4,opt,name=assist,proto3" json:"assist,omitempty"`
	Signature            []byte   `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Prepare) Reset()         { *m = Prepare{} }
func (m *Prepare) String() string { return proto.CompactTextString(m) }
func (*Prepare) ProtoMessage()    {}
func (*Prepare) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d30f2fcdff47131, []int{2}
}

func (m *Prepare) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Prepare.Unmarshal(m, b)
}
func (m *Prepare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Prepare.Marshal(b, m, deterministic)
}
func (m *Prepare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Prepare.Merge(m, src)
}
func (m *Prepare) XXX_Size() int {
	return xxx_messageInfo_Prepare.Size(m)
}
func (m *Prepare) XXX_DiscardUnknown() {
	xxx_messageInfo_Prepare.DiscardUnknown(m)
}

var xxx_messageInfo_Prepare proto.InternalMessageInfo

func (m *Prepare) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *Prepare) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *Prepare) GetDigest() string {
	if m != nil {
		return m.Digest
	}
	return ""
}

func (m *Prepare) GetAssist() bool {
	if m != nil {
		return m.Assist
	}
	return false
}

func (m *Prepare) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type PreparedProof struct {
	// Message that wraps a Commit message.
	Commit *Message `protobuf:"bytes,1,opt,name=commit,proto3" json:"commit,omitempty"`
	// The signatures are signatures originated
	// from prepare messages, and they are all
	// signatures on the same payload which is
	// the ASN1 marshalling of:
	// 	View   int64
	//	Seq    int64
	//	Digest string
	// that should match the attached commit.
	SignaturesByIds      map[uint64][]byte `protobuf:"bytes,2,rep,name=signatures_by_ids,json=signaturesByIds,proto3" json:"signatures_by_ids,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PreparedProof) Reset()         { *m = PreparedProof{} }
func (m *PreparedProof) String() string { return proto.CompactTextString(m) }
func (*PreparedProof) ProtoMessage()    {}
func (*PreparedProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d30f2fcdff47131, []int{3}
}

func (m *PreparedProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PreparedProof.Unmarshal(m, b)
}
func (m *PreparedProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PreparedProof.Marshal(b, m, deterministic)
}
func (m *PreparedProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PreparedProof.Merge(m, src)
}
func (m *PreparedProof) XXX_Size() int {
	return xxx_messageInfo_PreparedProof.Size(m)
}
func (m *PreparedProof) XXX_DiscardUnknown() {
	xxx_messageInfo_PreparedProof.DiscardUnknown(m)
}

var xxx_messageInfo_PreparedProof proto.InternalMessageInfo

func (m *PreparedProof) GetCommit() *Message {
	if m != nil {
		return m.Commit
	}
	return nil
}

func (m *PreparedProof) GetSignaturesByIds() map[uint64][]byte {
	if m != nil {
		return m.SignaturesByIds
	}
	return nil
}

type ProposedRecord struct {
	PrePrepare           *PrePrepare `protobuf:"bytes,1,opt,name=pre_prepare,json=prePrepare,proto3" json:"pre_prepare,omitempty"`
	Prepare              *Prepare    `protobuf:"bytes,2,opt,name=prepare,proto3" json:"prepare,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ProposedRecord) Reset()         { *m = ProposedRecord{} }
func (m *ProposedRecord) String() string { return proto.CompactTextString(m) }
func (*ProposedRecord) ProtoMessage()    {}
func (*ProposedRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d30f2fcdff47131, []int{4}
}

func (m *ProposedRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProposedRecord.Unmarshal(m, b)
}
func (m *ProposedRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProposedRecord.Marshal(b, m, deterministic)
}
func (m *ProposedRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProposedRecord.Merge(m, src)
}
func (m *ProposedRecord) XXX_Size() int {
	return xxx_messageInfo_ProposedRecord.Size(m)
}
func (m *ProposedRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_ProposedRecord.DiscardUnknown(m)
}

var xxx_messageInfo_ProposedRecord proto.InternalMessageInfo

func (m *ProposedRecord) GetPrePrepare() *PrePrepare {
	if m != nil {
		return m.PrePrepare
	}
	return nil
}

func (m *ProposedRecord) GetPrepare() *Prepare {
	if m != nil {
		return m.Prepare
	}
	return nil
}

type Commit struct {
	View                 uint64     `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	Seq                  uint64     `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Digest               string     `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	Signature            *Signature `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	Assist               bool       `protobuf:"varint,5,opt,name=assist,proto3" json:"assist,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Commit) Reset()         { *m = Commit{} }
func (m *Commit) String() string { return proto.CompactTextString(m) }
func (*Commit) ProtoMessage()    {}
func (*Commit) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d30f2fcdff47131, []int{5}
}

func (m *Commit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Commit.Unmarshal(m, b)
}
func (m *Commit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Commit.Marshal(b, m, deterministic)
}
func (m *Commit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Commit.Merge(m, src)
}
func (m *Commit) XXX_Size() int {
	return xxx_messageInfo_Commit.Size(m)
}
func (m *Commit) XXX_DiscardUnknown() {
	xxx_messageInfo_Commit.DiscardUnknown(m)
}

var xxx_messageInfo_Commit proto.InternalMessageInfo

func (m *Commit) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *Commit) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *Commit) GetDigest() string {
	if m != nil {
		return m.Digest
	}
	return ""
}

func (m *Commit) GetSignature() *Signature {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Commit) GetAssist() bool {
	if m != nil {
		return m.Assist
	}
	return false
}

type Error struct {
	View                 uint64   `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	Seq                  uint64   `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Digest               string   `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	Reason               string   `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d30f2fcdff47131, []int{6}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *Error) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *Error) GetDigest() string {
	if m != nil {
		return m.Digest
	}
	return ""
}

func (m *Error) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type ViewChange struct {
	NextView             uint64   `protobuf:"varint,1,opt,name=next_view,json=nextView,proto3" json:"next_view,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ViewChange) Reset()         { *m = ViewChange{} }
func (m *ViewChange) String() string { return proto.CompactTextString(m) }
func (*ViewChange) ProtoMessage()    {}
func (*ViewChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d30f2fcdff47131, []int{7}
}

func (m *ViewChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewChange.Unmarshal(m, b)
}
func (m *ViewChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewChange.Marshal(b, m, deterministic)
}
func (m *ViewChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewChange.Merge(m, src)
}
func (m *ViewChange) XXX_Size() int {
	return xxx_messageInfo_ViewChange.Size(m)
}
func (m *ViewChange) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewChange.DiscardUnknown(m)
}

var xxx_messageInfo_ViewChange proto.InternalMessageInfo

func (m *ViewChange) GetNextView() uint64 {
	if m != nil {
		return m.NextView
	}
	return 0
}

func (m *ViewChange) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type ViewData struct {
	NextView               uint64       `protobuf:"varint,1,opt,name=next_view,json=nextView,proto3" json:"next_view,omitempty"`
	LastDecision           *Proposal    `protobuf:"bytes,2,opt,name=last_decision,json=lastDecision,proto3" json:"last_decision,omitempty"`
	LastDecisionSignatures []*Signature `protobuf:"bytes,3,rep,name=last_decision_signatures,json=lastDecisionSignatures,proto3" json:"last_decision_signatures,omitempty"`
	LastPrePrepare         *PrePrepare  `protobuf:"bytes,4,opt,name=last_pre_prepare,json=lastPrePrepare,proto3" json:"last_pre_prepare,omitempty"`
	LastPrepare            *Prepare     `protobuf:"bytes,5,opt,name=last_prepare,json=lastPrepare,proto3" json:"last_prepare,omitempty"`
	LastCommit             *Commit      `protobuf:"bytes,6,opt,name=last_commit,json=lastCommit,proto3" json:"last_commit,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}     `json:"-"`
	XXX_unrecognized       []byte       `json:"-"`
	XXX_sizecache          int32        `json:"-"`
}

func (m *ViewData) Reset()         { *m = ViewData{} }
func (m *ViewData) String() string { return proto.CompactTextString(m) }
func (*ViewData) ProtoMessage()    {}
func (*ViewData) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d30f2fcdff47131, []int{8}
}

func (m *ViewData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewData.Unmarshal(m, b)
}
func (m *ViewData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewData.Marshal(b, m, deterministic)
}
func (m *ViewData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewData.Merge(m, src)
}
func (m *ViewData) XXX_Size() int {
	return xxx_messageInfo_ViewData.Size(m)
}
func (m *ViewData) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewData.DiscardUnknown(m)
}

var xxx_messageInfo_ViewData proto.InternalMessageInfo

func (m *ViewData) GetNextView() uint64 {
	if m != nil {
		return m.NextView
	}
	return 0
}

func (m *ViewData) GetLastDecision() *Proposal {
	if m != nil {
		return m.LastDecision
	}
	return nil
}

func (m *ViewData) GetLastDecisionSignatures() []*Signature {
	if m != nil {
		return m.LastDecisionSignatures
	}
	return nil
}

func (m *ViewData) GetLastPrePrepare() *PrePrepare {
	if m != nil {
		return m.LastPrePrepare
	}
	return nil
}

func (m *ViewData) GetLastPrepare() *Prepare {
	if m != nil {
		return m.LastPrepare
	}
	return nil
}

func (m *ViewData) GetLastCommit() *Commit {
	if m != nil {
		return m.LastCommit
	}
	return nil
}

type SignedViewData struct {
	RawViewData          []byte   `protobuf:"bytes,1,opt,name=raw_view_data,json=rawViewData,proto3" json:"raw_view_data,omitempty"`
	Signer               uint64   `protobuf:"varint,2,opt,name=signer,proto3" json:"signer,omitempty"`
	Signature            []byte   `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignedViewData) Reset()         { *m = SignedViewData{} }
func (m *SignedViewData) String() string { return proto.CompactTextString(m) }
func (*SignedViewData) ProtoMessage()    {}
func (*SignedViewData) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d30f2fcdff47131, []int{9}
}

func (m *SignedViewData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedViewData.Unmarshal(m, b)
}
func (m *SignedViewData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedViewData.Marshal(b, m, deterministic)
}
func (m *SignedViewData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedViewData.Merge(m, src)
}
func (m *SignedViewData) XXX_Size() int {
	return xxx_messageInfo_SignedViewData.Size(m)
}
func (m *SignedViewData) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedViewData.DiscardUnknown(m)
}

var xxx_messageInfo_SignedViewData proto.InternalMessageInfo

func (m *SignedViewData) GetRawViewData() []byte {
	if m != nil {
		return m.RawViewData
	}
	return nil
}

func (m *SignedViewData) GetSigner() uint64 {
	if m != nil {
		return m.Signer
	}
	return 0
}

func (m *SignedViewData) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type NewView struct {
	SignedViewData       []*SignedViewData `protobuf:"bytes,2,rep,name=signed_view_data,json=signedViewData,proto3" json:"signed_view_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *NewView) Reset()         { *m = NewView{} }
func (m *NewView) String() string { return proto.CompactTextString(m) }
func (*NewView) ProtoMessage()    {}
func (*NewView) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d30f2fcdff47131, []int{10}
}

func (m *NewView) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewView.Unmarshal(m, b)
}
func (m *NewView) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewView.Marshal(b, m, deterministic)
}
func (m *NewView) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewView.Merge(m, src)
}
func (m *NewView) XXX_Size() int {
	return xxx_messageInfo_NewView.Size(m)
}
func (m *NewView) XXX_DiscardUnknown() {
	xxx_messageInfo_NewView.DiscardUnknown(m)
}

var xxx_messageInfo_NewView proto.InternalMessageInfo

func (m *NewView) GetSignedViewData() []*SignedViewData {
	if m != nil {
		return m.SignedViewData
	}
	return nil
}

type HeartBeat struct {
	View                 uint64   `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	Seq                  uint64   `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartBeat) Reset()         { *m = HeartBeat{} }
func (m *HeartBeat) String() string { return proto.CompactTextString(m) }
func (*HeartBeat) ProtoMessage()    {}
func (*HeartBeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d30f2fcdff47131, []int{11}
}

func (m *HeartBeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartBeat.Unmarshal(m, b)
}
func (m *HeartBeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartBeat.Marshal(b, m, deterministic)
}
func (m *HeartBeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartBeat.Merge(m, src)
}
func (m *HeartBeat) XXX_Size() int {
	return xxx_messageInfo_HeartBeat.Size(m)
}
func (m *HeartBeat) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartBeat.DiscardUnknown(m)
}

var xxx_messageInfo_HeartBeat proto.InternalMessageInfo

func (m *HeartBeat) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *HeartBeat) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

type Signature struct {
	Signer               uint64   `protobuf:"varint,1,opt,name=signer,proto3" json:"signer,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Msg                  []byte   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Signature) Reset()         { *m = Signature{} }
func (m *Signature) String() string { return proto.CompactTextString(m) }
func (*Signature) ProtoMessage()    {}
func (*Signature) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d30f2fcdff47131, []int{12}
}

func (m *Signature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Signature.Unmarshal(m, b)
}
func (m *Signature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Signature.Marshal(b, m, deterministic)
}
func (m *Signature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Signature.Merge(m, src)
}
func (m *Signature) XXX_Size() int {
	return xxx_messageInfo_Signature.Size(m)
}
func (m *Signature) XXX_DiscardUnknown() {
	xxx_messageInfo_Signature.DiscardUnknown(m)
}

var xxx_messageInfo_Signature proto.InternalMessageInfo

func (m *Signature) GetSigner() uint64 {
	if m != nil {
		return m.Signer
	}
	return 0
}

func (m *Signature) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Signature) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

type Proposal struct {
	Header               []byte   `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Payload              []byte   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Metadata             []byte   `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	VerificationSequence uint64   `protobuf:"varint,4,opt,name=verification_sequence,json=verificationSequence,proto3" json:"verification_sequence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Proposal) Reset()         { *m = Proposal{} }
func (m *Proposal) String() string { return proto.CompactTextString(m) }
func (*Proposal) ProtoMessage()    {}
func (*Proposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d30f2fcdff47131, []int{13}
}

func (m *Proposal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Proposal.Unmarshal(m, b)
}
func (m *Proposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Proposal.Marshal(b, m, deterministic)
}
func (m *Proposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proposal.Merge(m, src)
}
func (m *Proposal) XXX_Size() int {
	return xxx_messageInfo_Proposal.Size(m)
}
func (m *Proposal) XXX_DiscardUnknown() {
	xxx_messageInfo_Proposal.DiscardUnknown(m)
}

var xxx_messageInfo_Proposal proto.InternalMessageInfo

func (m *Proposal) GetHeader() []byte {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Proposal) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Proposal) GetMetadata() []byte {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Proposal) GetVerificationSequence() uint64 {
	if m != nil {
		return m.VerificationSequence
	}
	return 0
}

type ViewMetadata struct {
	ViewId               uint64   `protobuf:"varint,1,opt,name=view_id,json=viewId,proto3" json:"view_id,omitempty"`
	LatestSequence       uint64   `protobuf:"varint,2,opt,name=latest_sequence,json=latestSequence,proto3" json:"latest_sequence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ViewMetadata) Reset()         { *m = ViewMetadata{} }
func (m *ViewMetadata) String() string { return proto.CompactTextString(m) }
func (*ViewMetadata) ProtoMessage()    {}
func (*ViewMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d30f2fcdff47131, []int{14}
}

func (m *ViewMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewMetadata.Unmarshal(m, b)
}
func (m *ViewMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewMetadata.Marshal(b, m, deterministic)
}
func (m *ViewMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewMetadata.Merge(m, src)
}
func (m *ViewMetadata) XXX_Size() int {
	return xxx_messageInfo_ViewMetadata.Size(m)
}
func (m *ViewMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ViewMetadata proto.InternalMessageInfo

func (m *ViewMetadata) GetViewId() uint64 {
	if m != nil {
		return m.ViewId
	}
	return 0
}

func (m *ViewMetadata) GetLatestSequence() uint64 {
	if m != nil {
		return m.LatestSequence
	}
	return 0
}

type SavedMessage struct {
	// Types that are valid to be assigned to Content:
	//	*SavedMessage_ProposedRecord
	//	*SavedMessage_PreparedProof
	Content              isSavedMessage_Content `protobuf_oneof:"content"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SavedMessage) Reset()         { *m = SavedMessage{} }
func (m *SavedMessage) String() string { return proto.CompactTextString(m) }
func (*SavedMessage) ProtoMessage()    {}
func (*SavedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d30f2fcdff47131, []int{15}
}

func (m *SavedMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SavedMessage.Unmarshal(m, b)
}
func (m *SavedMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SavedMessage.Marshal(b, m, deterministic)
}
func (m *SavedMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SavedMessage.Merge(m, src)
}
func (m *SavedMessage) XXX_Size() int {
	return xxx_messageInfo_SavedMessage.Size(m)
}
func (m *SavedMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SavedMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SavedMessage proto.InternalMessageInfo

type isSavedMessage_Content interface {
	isSavedMessage_Content()
}

type SavedMessage_ProposedRecord struct {
	ProposedRecord *ProposedRecord `protobuf:"bytes,1,opt,name=proposed_record,json=proposedRecord,proto3,oneof"`
}

type SavedMessage_PreparedProof struct {
	PreparedProof *PreparedProof `protobuf:"bytes,2,opt,name=prepared_proof,json=preparedProof,proto3,oneof"`
}

func (*SavedMessage_ProposedRecord) isSavedMessage_Content() {}

func (*SavedMessage_PreparedProof) isSavedMessage_Content() {}

func (m *SavedMessage) GetContent() isSavedMessage_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *SavedMessage) GetProposedRecord() *ProposedRecord {
	if x, ok := m.GetContent().(*SavedMessage_ProposedRecord); ok {
		return x.ProposedRecord
	}
	return nil
}

func (m *SavedMessage) GetPreparedProof() *PreparedProof {
	if x, ok := m.GetContent().(*SavedMessage_PreparedProof); ok {
		return x.PreparedProof
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SavedMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SavedMessage_ProposedRecord)(nil),
		(*SavedMessage_PreparedProof)(nil),
	}
}

func init() {
	proto.RegisterType((*Message)(nil), "smartbftprotos.Message")
	proto.RegisterType((*PrePrepare)(nil), "smartbftprotos.PrePrepare")
	proto.RegisterType((*Prepare)(nil), "smartbftprotos.Prepare")
	proto.RegisterType((*PreparedProof)(nil), "smartbftprotos.PreparedProof")
	proto.RegisterMapType((map[uint64][]byte)(nil), "smartbftprotos.PreparedProof.SignaturesByIdsEntry")
	proto.RegisterType((*ProposedRecord)(nil), "smartbftprotos.ProposedRecord")
	proto.RegisterType((*Commit)(nil), "smartbftprotos.Commit")
	proto.RegisterType((*Error)(nil), "smartbftprotos.Error")
	proto.RegisterType((*ViewChange)(nil), "smartbftprotos.ViewChange")
	proto.RegisterType((*ViewData)(nil), "smartbftprotos.ViewData")
	proto.RegisterType((*SignedViewData)(nil), "smartbftprotos.SignedViewData")
	proto.RegisterType((*NewView)(nil), "smartbftprotos.NewView")
	proto.RegisterType((*HeartBeat)(nil), "smartbftprotos.HeartBeat")
	proto.RegisterType((*Signature)(nil), "smartbftprotos.Signature")
	proto.RegisterType((*Proposal)(nil), "smartbftprotos.Proposal")
	proto.RegisterType((*ViewMetadata)(nil), "smartbftprotos.ViewMetadata")
	proto.RegisterType((*SavedMessage)(nil), "smartbftprotos.SavedMessage")
}

func init() { proto.RegisterFile("smartbftprotos/messages.proto", fileDescriptor_0d30f2fcdff47131) }

var fileDescriptor_0d30f2fcdff47131 = []byte{
	// 926 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x16, 0xf5, 0xcf, 0x91, 0x2c, 0xbb, 0x0b, 0xc7, 0x61, 0xdd, 0x26, 0x08, 0x78, 0x69, 0x2e,
	0x75, 0x1a, 0xbb, 0x40, 0x0a, 0x17, 0x3e, 0xd4, 0x71, 0x0a, 0x19, 0x45, 0x0a, 0x63, 0x05, 0xf4,
	0xd6, 0x12, 0x2b, 0x71, 0x2c, 0xb1, 0x95, 0x48, 0x66, 0x77, 0x2d, 0x55, 0x87, 0x02, 0x7d, 0x81,
	0x9e, 0xfb, 0x12, 0x7d, 0xa1, 0xde, 0xfb, 0x0c, 0x3d, 0x17, 0xfb, 0x43, 0x8a, 0x54, 0x19, 0x25,
	0x81, 0x6f, 0x3b, 0xbb, 0xf3, 0x7d, 0xd4, 0xce, 0x7c, 0xf3, 0xad, 0xe0, 0x91, 0x58, 0x30, 0x2e,
	0xc7, 0xb7, 0x32, 0xe5, 0x89, 0x4c, 0xc4, 0xb3, 0x05, 0x0a, 0xc1, 0xa6, 0x28, 0x4e, 0x74, 0x4c,
	0x06, 0xe5, 0x63, 0xff, 0xef, 0x06, 0x74, 0x5e, 0x9b, 0x14, 0x72, 0x01, 0xbd, 0x94, 0x63, 0x90,
	0x72, 0x4c, 0x19, 0x47, 0xcf, 0x79, 0xe2, 0x3c, 0xed, 0x9d, 0x1e, 0x9f, 0x94, 0x11, 0x27, 0x37,
	0x1c, 0x6f, 0x4c, 0xc6, 0xb0, 0x46, 0x21, 0xcd, 0x23, 0x72, 0x06, 0x9d, 0x0c, 0x5a, 0xd7, 0xd0,
	0x87, 0x15, 0x50, 0x8b, 0xcb, 0x32, 0xc9, 0x17, 0xd0, 0x9e, 0x24, 0x8b, 0x45, 0x24, 0xbd, 0x86,
	0xc6, 0x1c, 0x6d, 0x63, 0x5e, 0xea, 0xd3, 0x61, 0x8d, 0xda, 0x3c, 0xf2, 0x39, 0xb4, 0x90, 0xf3,
	0x84, 0x7b, 0x4d, 0x0d, 0x78, 0xb0, 0x0d, 0x78, 0xa5, 0x0e, 0x87, 0x35, 0x6a, 0xb2, 0xd4, 0xa5,
	0x96, 0x11, 0xae, 0x82, 0xc9, 0x8c, 0xc5, 0x53, 0xf4, 0x5a, 0xd5, 0x97, 0xfa, 0x21, 0xc2, 0xd5,
	0x4b, 0x9d, 0xa1, 0x2e, 0xb5, 0xcc, 0x23, 0x72, 0x01, 0xae, 0x86, 0x87, 0x4c, 0x32, 0xaf, 0xad,
	0xc1, 0x8f, 0xb7, 0xc1, 0xa3, 0x68, 0x1a, 0x63, 0xa8, 0x28, 0xae, 0x98, 0x64, 0xc3, 0x1a, 0xed,
	0x2e, 0xed, 0x9a, 0x7c, 0x09, 0xdd, 0x18, 0x57, 0x81, 0x8a, 0xbd, 0x4e, 0x75, 0x51, 0xbe, 0xc7,
	0x95, 0x82, 0xaa, 0xa2, 0xc4, 0x66, 0x49, 0xce, 0x01, 0x66, 0xc8, 0xb8, 0x0c, 0xc6, 0xc8, 0xa4,
	0xd7, 0xd5, 0xb8, 0x8f, 0xb7, 0x71, 0x43, 0x95, 0x71, 0x89, 0x4c, 0xd5, 0xc6, 0x9d, 0x65, 0xc1,
	0xa5, 0x0b, 0x9d, 0x49, 0x12, 0x4b, 0x8c, 0xa5, 0x3f, 0x03, 0xd8, 0x34, 0x8b, 0x10, 0x68, 0xea,
	0x9f, 0xa1, 0xda, 0xda, 0xa4, 0x7a, 0x4d, 0x0e, 0xa0, 0x21, 0xf0, 0x8d, 0x6e, 0x57, 0x93, 0xaa,
	0xa5, 0xfa, 0xc1, 0x29, 0x4f, 0xd2, 0x44, 0xb0, 0xb9, 0xed, 0x88, 0xf7, 0xff, 0x2e, 0x9a, 0x73,
	0x9a, 0x67, 0xfa, 0xbf, 0x41, 0xe7, 0xc3, 0x3e, 0x73, 0x04, 0xed, 0x30, 0x9a, 0xa2, 0x30, 0x6d,
	0x77, 0xa9, 0x8d, 0xd4, 0x3e, 0x13, 0x22, 0x12, 0x52, 0x77, 0xb7, 0x4b, 0x6d, 0x44, 0x3e, 0x05,
	0x57, 0x44, 0xd3, 0x98, 0xc9, 0x3b, 0x6e, 0x7a, 0xd8, 0xa7, 0x9b, 0x0d, 0xff, 0x1f, 0x07, 0xf6,
	0xec, 0xf7, 0xc3, 0x1b, 0x9e, 0x24, 0xb7, 0xe4, 0x59, 0x2e, 0x2b, 0xa7, 0xba, 0xea, 0x56, 0xf3,
	0xb9, 0xaa, 0x7e, 0x82, 0x8f, 0x72, 0x3e, 0x11, 0x8c, 0xd7, 0x41, 0x14, 0x0a, 0xaf, 0xfe, 0xa4,
	0xf1, 0xb4, 0x77, 0x7a, 0xfa, 0x16, 0x19, 0x9b, 0x4f, 0xe9, 0xee, 0x1b, 0xd8, 0xe5, 0xfa, 0x3a,
	0x14, 0xaf, 0x62, 0xc9, 0xd7, 0x74, 0x5f, 0x94, 0x77, 0x8f, 0x2f, 0xe1, 0xb0, 0x2a, 0x51, 0x95,
	0xe6, 0x17, 0x5c, 0xdb, 0x6a, 0xa9, 0x25, 0x39, 0x84, 0xd6, 0x92, 0xcd, 0xef, 0xcc, 0x10, 0xf5,
	0xa9, 0x09, 0xce, 0xeb, 0x5f, 0x39, 0xfe, 0xef, 0x0e, 0x0c, 0x4c, 0xf1, 0x31, 0xa4, 0x38, 0x49,
	0x78, 0x48, 0xbe, 0xfe, 0xc0, 0x91, 0x2d, 0x0d, 0xec, 0xf3, 0xf7, 0x1d, 0xd8, 0x7c, 0x5c, 0xfd,
	0x3f, 0x1d, 0x68, 0x9b, 0x89, 0xbc, 0x67, 0xa3, 0x5f, 0x14, 0x1b, 0xda, 0xac, 0x56, 0x78, 0x5e,
	0xb0, 0x42, 0xaf, 0x0b, 0x0a, 0x69, 0x15, 0x15, 0xe2, 0xff, 0x08, 0x2d, 0x3d, 0xf9, 0xf7, 0x17,
	0x20, 0x47, 0x26, 0x92, 0x58, 0xff, 0x28, 0x97, 0xda, 0xc8, 0xff, 0x06, 0x60, 0xe3, 0x11, 0xe4,
	0x13, 0x70, 0x63, 0xfc, 0x55, 0x06, 0x85, 0x0f, 0x75, 0xd5, 0x86, 0x9e, 0xde, 0x0d, 0x45, 0xbd,
	0x44, 0xf1, 0x6f, 0x1d, 0xba, 0x99, 0x49, 0xec, 0x66, 0xb8, 0x80, 0xbd, 0x39, 0x13, 0x32, 0x08,
	0x71, 0x12, 0x89, 0xc8, 0x12, 0xed, 0x9a, 0xc4, 0xbe, 0x4a, 0xbf, 0xb2, 0xd9, 0x64, 0x04, 0x5e,
	0x09, 0x1e, 0x6c, 0xc4, 0xe8, 0x35, 0xb4, 0xa4, 0x77, 0x94, 0xfa, 0xa8, 0x48, 0xb5, 0x91, 0x2c,
	0xb9, 0x82, 0x03, 0x4d, 0x5a, 0x94, 0x5b, 0xf3, 0x9d, 0x72, 0x1b, 0x28, 0x4c, 0xc1, 0x84, 0xce,
	0xa1, 0x9f, 0xb1, 0x68, 0x86, 0xd6, 0x6e, 0xdd, 0xf5, 0x2c, 0x5c, 0x63, 0x5f, 0x80, 0x0e, 0x03,
	0x3b, 0xd8, 0xed, 0x5d, 0xef, 0x05, 0x05, 0x95, 0x6a, 0xd6, 0xfe, 0xcf, 0x30, 0x28, 0x5b, 0x34,
	0xf1, 0x61, 0x8f, 0x33, 0x63, 0xcb, 0xc6, 0xd9, 0x1d, 0x3d, 0x6b, 0x3d, 0xce, 0x56, 0x79, 0xce,
	0x11, 0xb4, 0x55, 0xdd, 0x90, 0x5b, 0xd9, 0xd8, 0xa8, 0x6c, 0x45, 0x8d, 0x6d, 0x2b, 0x1a, 0x41,
	0xc7, 0x1a, 0x3a, 0x19, 0xc2, 0x81, 0x86, 0x84, 0x85, 0xef, 0x18, 0x47, 0x79, 0xc7, 0x0b, 0x42,
	0x07, 0xa2, 0x14, 0xfb, 0xcf, 0xc1, 0xcd, 0xdd, 0xfe, 0xfd, 0xf4, 0xed, 0x7f, 0x07, 0xee, 0xa8,
	0x38, 0x33, 0xf6, 0x2a, 0x4e, 0xe9, 0x2a, 0x95, 0x56, 0xa3, 0xc8, 0x16, 0x62, 0x6a, 0xaf, 0xa6,
	0x96, 0xfe, 0x1f, 0x0e, 0x74, 0x33, 0xad, 0x29, 0xb2, 0x19, 0xb2, 0xd0, 0x92, 0xf5, 0xa9, 0x8d,
	0x88, 0x07, 0x9d, 0x94, 0xad, 0xe7, 0x09, 0x0b, 0x2d, 0x5d, 0x16, 0x92, 0x63, 0xe8, 0x2e, 0x50,
	0x32, 0x5d, 0x00, 0xc3, 0x9a, 0xc7, 0xe4, 0x0c, 0x1e, 0x2c, 0x91, 0x47, 0xb7, 0xd1, 0x84, 0x49,
	0x2d, 0x55, 0x7c, 0x73, 0x87, 0xf1, 0xc4, 0x68, 0xab, 0x49, 0x0f, 0x8b, 0x87, 0x23, 0x7b, 0xe6,
	0xdf, 0x40, 0x5f, 0xd5, 0xe6, 0x75, 0x46, 0xf2, 0x10, 0x3a, 0xba, 0xc4, 0x51, 0x98, 0x5d, 0x50,
	0x85, 0xd7, 0x21, 0xf9, 0x0c, 0xf6, 0xe7, 0x4c, 0xa2, 0x90, 0x1b, 0x5e, 0x53, 0xa3, 0x81, 0xd9,
	0xce, 0x19, 0xff, 0x72, 0xa0, 0x3f, 0x62, 0x4b, 0x0c, 0xb3, 0xff, 0x42, 0xd7, 0xb0, 0x9f, 0x5a,
	0xab, 0x0d, 0xb8, 0xf6, 0x5a, 0x6b, 0xae, 0x8f, 0xab, 0x87, 0x30, 0x73, 0xe4, 0x61, 0x8d, 0x0e,
	0xd2, 0xb2, 0x47, 0x7f, 0x0b, 0x03, 0x2b, 0xf7, 0x30, 0x48, 0xd5, 0x93, 0x61, 0xc7, 0xf9, 0xd1,
	0xce, 0x77, 0x65, 0x58, 0xa3, 0x7b, 0x69, 0x71, 0xa3, 0xf0, 0xb2, 0x8f, 0xdb, 0x1a, 0x71, 0xf6,
	0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x94, 0x56, 0x65, 0xa9, 0xed, 0x09, 0x00, 0x00,
}
