// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import types "github.com/SmartBFT-Go/consensus/pkg/types"

// Application is an autogenerated mock type for the Application type
type Application struct {
	mock.Mock
}

// Deliver provides a mock function with given fields: proposal, signature
func (_m *Application) Deliver(proposal types.Proposal, signature []types.Signature) {
	_m.Called(proposal, signature)
}
