// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	types "github.com/SmartBFT-Go/consensus/pkg/types"
	mock "github.com/stretchr/testify/mock"
)

// Application is an autogenerated mock type for the Application type
type Application struct {
	mock.Mock
}

// Deliver provides a mock function with given fields: proposal, signature
func (_m *Application) Deliver(proposal types.Proposal, signature []types.Signature) bool {
	ret := _m.Called(proposal, signature)

	var r0 bool
	if rf, ok := ret.Get(0).(func(types.Proposal, []types.Signature) bool); ok {
		r0 = rf(proposal, signature)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
