// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import types "github.com/SmartBFT-Go/consensus/pkg/types"

// AssemblerMock is an autogenerated mock type for the AssemblerMock type
type AssemblerMock struct {
	mock.Mock
}

// AssembleProposal provides a mock function with given fields: metadata, requests
func (_m *AssemblerMock) AssembleProposal(metadata []byte, requests [][]byte) (types.Proposal, [][]byte) {
	ret := _m.Called(metadata, requests)

	var r0 types.Proposal
	if rf, ok := ret.Get(0).(func([]byte, [][]byte) types.Proposal); ok {
		r0 = rf(metadata, requests)
	} else {
		r0 = ret.Get(0).(types.Proposal)
	}

	var r1 [][]byte
	if rf, ok := ret.Get(1).(func([]byte, [][]byte) [][]byte); ok {
		r1 = rf(metadata, requests)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([][]byte)
		}
	}

	return r0, r1
}
