// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"

// Batcher is an autogenerated mock type for the Batcher type
type Batcher struct {
	mock.Mock
}

// BatchRemainder provides a mock function with given fields: remainder
func (_m *Batcher) BatchRemainder(remainder [][]byte) {
	_m.Called(remainder)
}

// NextBatch provides a mock function with given fields: ctx
func (_m *Batcher) NextBatch(ctx context.Context) [][]byte {
	ret := _m.Called(ctx)

	var r0 [][]byte
	if rf, ok := ret.Get(0).(func(context.Context) [][]byte); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]byte)
		}
	}

	return r0
}
