// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import bft "github.com/SmartBFT-Go/consensus/internal/bft"
import mock "github.com/stretchr/testify/mock"

// Batcher is an autogenerated mock type for the Batcher type
type Batcher struct {
	mock.Mock
}

// BatchRemainder provides a mock function with given fields: remainder
func (_m *Batcher) BatchRemainder(remainder []bft.Request) {
	_m.Called(remainder)
}

// NextBatch provides a mock function with given fields:
func (_m *Batcher) NextBatch() []bft.Request {
	ret := _m.Called()

	var r0 []bft.Request
	if rf, ok := ret.Get(0).(func() []bft.Request); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]bft.Request)
		}
	}

	return r0
}
