// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import smartbftprotos "github.com/SmartBFT-Go/consensus/smartbftprotos"

// CommMock is an autogenerated mock type for the CommMock type
type CommMock struct {
	mock.Mock
}

// BroadcastConsensus provides a mock function with given fields: m
func (_m *CommMock) BroadcastConsensus(m *smartbftprotos.Message) {
	_m.Called(m)
}

// SendConsensus provides a mock function with given fields: targetID, m
func (_m *CommMock) SendConsensus(targetID uint64, m *smartbftprotos.Message) {
	_m.Called(targetID, m)
}

// SendTransaction provides a mock function with given fields: targetID, request
func (_m *CommMock) SendTransaction(targetID uint64, request []byte) {
	_m.Called(targetID, request)
}
