// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import smartbftprotos "github.com/SmartBFT-Go/consensus/smartbftprotos"

// Comm is an autogenerated mock type for the Comm type
type Comm struct {
	mock.Mock
}

// BroadcastConsensus provides a mock function with given fields: m
func (_m *Comm) BroadcastConsensus(m *smartbftprotos.Message) {
	_m.Called(m)
}
