// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	types "github.com/SmartBFT-Go/consensus/pkg/types"
	mock "github.com/stretchr/testify/mock"
)

// Decider is an autogenerated mock type for the Decider type
type Decider struct {
	mock.Mock
}

// Decide provides a mock function with given fields: proposal, signatures, requests, abortChan
func (_m *Decider) Decide(proposal types.Proposal, signatures []types.Signature, requests []types.RequestInfo, abortChan <-chan struct{}) {
	_m.Called(proposal, signatures, requests, abortChan)
}
