// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import types "github.com/SmartBFT-Go/consensus/pkg/types"

// Decider is an autogenerated mock type for the Decider type
type Decider struct {
	mock.Mock
}

// Decide provides a mock function with given fields: proposal, signatures
func (_m *Decider) Decide(proposal types.Proposal, signatures []types.Signature) {
	_m.Called(proposal, signatures)
}
