// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// FailureDetector is an autogenerated mock type for the FailureDetector type
type FailureDetector struct {
	mock.Mock
}

// Complain provides a mock function with given fields: viewNum, stopView
func (_m *FailureDetector) Complain(viewNum uint64, stopView bool) {
	_m.Called(viewNum, stopView)
}
