// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// FailureDetector is an autogenerated mock type for the FailureDetector type
type FailureDetector struct {
	mock.Mock
}

// Complain provides a mock function with given fields: stopView
func (_m *FailureDetector) Complain(stopView bool) {
	_m.Called(stopView)
}
