// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// HeartbeatResponseSyncHandler is an autogenerated mock type for the HeartbeatResponseSyncHandler type
type HeartbeatResponseSyncHandler struct {
	mock.Mock
}

// OnHeartbeatResponseSync provides a mock function with given fields: view
func (_m *HeartbeatResponseSyncHandler) OnHeartbeatResponseSync(view uint64) {
	_m.Called(view)
}
