// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// HeartbeatTimeoutHandler is an autogenerated mock type for the HeartbeatTimeoutHandler type
type HeartbeatTimeoutHandler struct {
	mock.Mock
}

// OnHeartbeatTimeout provides a mock function with given fields: view, leaderID
func (_m *HeartbeatTimeoutHandler) OnHeartbeatTimeout(view uint64, leaderID uint64) {
	_m.Called(view, leaderID)
}
