// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import smartbftprotos "github.com/SmartBFT-Go/consensus/smartbftprotos"

// LeaderMonitor is an autogenerated mock type for the LeaderMonitor type
type LeaderMonitor struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *LeaderMonitor) Close() {
	_m.Called()
}

// ProcessMsg provides a mock function with given fields: sender, msg
func (_m *LeaderMonitor) ProcessMsg(sender uint64, msg *smartbftprotos.HeartBeat) {
	_m.Called(sender, msg)
}

// StartFollower provides a mock function with given fields: view, leaderID
func (_m *LeaderMonitor) StartFollower(view uint64, leaderID uint64) {
	_m.Called(view, leaderID)
}

// StartLeader provides a mock function with given fields: view, leaderID
func (_m *LeaderMonitor) StartLeader(view uint64, leaderID uint64) {
	_m.Called(view, leaderID)
}
