// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Pruner is an autogenerated mock type for the Pruner type
type Pruner struct {
	mock.Mock
}

// MaybePruneRevokedRequests provides a mock function with given fields:
func (_m *Pruner) MaybePruneRevokedRequests() {
	_m.Called()
}
