// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// RequestPool is an autogenerated mock type for the RequestPool type
type RequestPool struct {
	mock.Mock
}

// Submit provides a mock function with given fields: request
func (_m *RequestPool) Submit(request []byte) {
	_m.Called(request)
}
