// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// RequestTimeoutHandler is an autogenerated mock type for the RequestTimeoutHandler type
type RequestTimeoutHandler struct {
	mock.Mock
}

// OnLeaderFwdRequestTimeout provides a mock function with given fields: request
func (_m *RequestTimeoutHandler) OnLeaderFwdRequestTimeout(request []byte) {
	_m.Called(request)
}

// OnRequestTimeout provides a mock function with given fields: request
func (_m *RequestTimeoutHandler) OnRequestTimeout(request []byte) {
	_m.Called(request)
}
