// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import bft "github.com/SmartBFT-Go/consensus/internal/bft"
import mock "github.com/stretchr/testify/mock"
import types "github.com/SmartBFT-Go/consensus/pkg/types"

// RequestPool is an autogenerated mock type for the RequestPool type
type RequestPool struct {
	mock.Mock
}

// NextRequests provides a mock function with given fields: n
func (_m *RequestPool) NextRequests(n int) []bft.Request {
	ret := _m.Called(n)

	var r0 []bft.Request
	if rf, ok := ret.Get(0).(func(int) []bft.Request); ok {
		r0 = rf(n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]bft.Request)
		}
	}

	return r0
}

// RemoveRequest provides a mock function with given fields: request
func (_m *RequestPool) RemoveRequest(request types.RequestInfo) error {
	ret := _m.Called(request)

	var r0 error
	if rf, ok := ret.Get(0).(func(types.RequestInfo) error); ok {
		r0 = rf(request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Submit provides a mock function with given fields: request
func (_m *RequestPool) Submit(request []byte) error {
	ret := _m.Called(request)

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = rf(request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
