// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// RequestsTimer is an autogenerated mock type for the RequestsTimer type
type RequestsTimer struct {
	mock.Mock
}

// RestartTimers provides a mock function with given fields:
func (_m *RequestsTimer) RestartTimers() {
	_m.Called()
}

// StopTimers provides a mock function with given fields:
func (_m *RequestsTimer) StopTimers() {
	_m.Called()
}
