// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import types "github.com/SmartBFT-Go/consensus/pkg/types"

// RequestInspector is an autogenerated mock type for the RequestInspector type
type RequestInspector struct {
	mock.Mock
}

// RequestID provides a mock function with given fields: req
func (_m *RequestInspector) RequestID(req []byte) types.RequestInfo {
	ret := _m.Called(req)

	var r0 types.RequestInfo
	if rf, ok := ret.Get(0).(func([]byte) types.RequestInfo); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(types.RequestInfo)
	}

	return r0
}
