// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import bft "github.com/SmartBFT-Go/consensus/internal/bft"
import mock "github.com/stretchr/testify/mock"
import smartbftprotos "github.com/SmartBFT-Go/consensus/smartbftprotos"

// State is an autogenerated mock type for the State type
type State struct {
	mock.Mock
}

// Restore provides a mock function with given fields: _a0
func (_m *State) Restore(_a0 *bft.View) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*bft.View) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Save provides a mock function with given fields: message
func (_m *State) Save(message *smartbftprotos.Message) error {
	ret := _m.Called(message)

	var r0 error
	if rf, ok := ret.Get(0).(func(*smartbftprotos.Message) error); ok {
		r0 = rf(message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
