// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import smartbftprotos "github.com/SmartBFT-Go/consensus/smartbftprotos"

// SynchronizerMock is an autogenerated mock type for the SynchronizerMock type
type SynchronizerMock struct {
	mock.Mock
}

// Sync provides a mock function with given fields:
func (_m *SynchronizerMock) Sync() (smartbftprotos.ViewMetadata, uint64) {
	ret := _m.Called()

	var r0 smartbftprotos.ViewMetadata
	if rf, ok := ret.Get(0).(func() smartbftprotos.ViewMetadata); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(smartbftprotos.ViewMetadata)
	}

	var r1 uint64
	if rf, ok := ret.Get(1).(func() uint64); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(uint64)
	}

	return r0, r1
}
