// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ViewController is an autogenerated mock type for the ViewController type
type ViewController struct {
	mock.Mock
}

// ViewChanged provides a mock function with given fields: newViewNumber, newProposalSequence
func (_m *ViewController) ViewChanged(newViewNumber uint64, newProposalSequence uint64) {
	_m.Called(newViewNumber, newProposalSequence)
}
