// Code generated by mockery v2.26.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ViewController is an autogenerated mock type for the ViewController type
type ViewController struct {
	mock.Mock
}

// AbortView provides a mock function with given fields: view
func (_m *ViewController) AbortView(view uint64) {
	_m.Called(view)
}

// LockDoubleDelivery provides a mock function with given fields:
func (_m *ViewController) LockDoubleDelivery() {
	_m.Called()
}

// UnlockDoubleDelivery provides a mock function with given fields:
func (_m *ViewController) UnlockDoubleDelivery() {
	_m.Called()
}

// ViewChanged provides a mock function with given fields: newViewNumber, newProposalSequence
func (_m *ViewController) ViewChanged(newViewNumber uint64, newProposalSequence uint64) {
	_m.Called(newViewNumber, newProposalSequence)
}

type mockConstructorTestingTNewViewController interface {
	mock.TestingT
	Cleanup(func())
}

// NewViewController creates a new instance of ViewController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewViewController(t mockConstructorTestingTNewViewController) *ViewController {
	mock := &ViewController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
