// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test_message.proto

package naive

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FwdMessage struct {
	Sender               uint64   `protobuf:"varint,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Payload              []byte   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FwdMessage) Reset()         { *m = FwdMessage{} }
func (m *FwdMessage) String() string { return proto.CompactTextString(m) }
func (*FwdMessage) ProtoMessage()    {}
func (*FwdMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe93c4cad939e43a, []int{0}
}

func (m *FwdMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FwdMessage.Unmarshal(m, b)
}
func (m *FwdMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FwdMessage.Marshal(b, m, deterministic)
}
func (m *FwdMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FwdMessage.Merge(m, src)
}
func (m *FwdMessage) XXX_Size() int {
	return xxx_messageInfo_FwdMessage.Size(m)
}
func (m *FwdMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_FwdMessage.DiscardUnknown(m)
}

var xxx_messageInfo_FwdMessage proto.InternalMessageInfo

func (m *FwdMessage) GetSender() uint64 {
	if m != nil {
		return m.Sender
	}
	return 0
}

func (m *FwdMessage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*FwdMessage)(nil), "naive.FwdMessage")
}

func init() { proto.RegisterFile("test_message.proto", fileDescriptor_fe93c4cad939e43a) }

var fileDescriptor_fe93c4cad939e43a = []byte{
	// 105 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x49, 0x2d, 0x2e,
	0x89, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0xcd, 0x4b, 0xcc, 0x2c, 0x4b, 0x55, 0xb2, 0xe3, 0xe2, 0x72, 0x2b, 0x4f, 0xf1, 0x85, 0x48, 0x09,
	0x89, 0x71, 0xb1, 0x15, 0xa7, 0xe6, 0xa5, 0xa4, 0x16, 0x49, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x04,
	0x41, 0x79, 0x42, 0x12, 0x5c, 0xec, 0x05, 0x89, 0x95, 0x39, 0xf9, 0x89, 0x29, 0x12, 0x4c, 0x0a,
	0x8c, 0x1a, 0x3c, 0x41, 0x30, 0x6e, 0x12, 0x1b, 0xd8, 0x34, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x2c, 0x3b, 0x2f, 0xa2, 0x63, 0x00, 0x00, 0x00,
}
